// Code generated by generate_errors.sh. DO NOT EDIT.
package apperrors

var (
	UNKNOWN_DOMAIN = AppError{
		Key: "UNKNOWN_DOMAIN",
		Code: "CORE-VAL-999",
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Unknown domain error",
		Severity: "S1",
		Retryable: false,
	}

	INTERNAL_FALLBACK = AppError{
		Key: "INTERNAL_FALLBACK",
		Code: "CORE-INF-000",
		Status: 500,
		GRPCCode: "Internal",
		Message: "Internal server error",
		Severity: "S1",
		Retryable: false,
	}

)

var ErrorByCode = map[string]AppError{
	"CORE-VAL-999": UNKNOWN_DOMAIN,
	"CORE-INF-000": INTERNAL_FALLBACK,
}
