syntax = "proto3";

package iam.v1;

option go_package = "github.com/vokhanh12/refactor-rongstore-system/server/gen/proto/iam/v1/resources;resourcespb";
option java_package = "com.aliasadi.iam.v1.resources";
option java_multiple_files = true;

import "buf/validate/validate.proto";
import "core/common/v1/resources/auth_options.proto";
import "google/protobuf/timestamp.proto";

// ============================================================
// ENTITY
// ============================================================

message Permission {
  string id = 1;
  string code = 2;

  string name = 3;
  string description = 4;

  string resource = 5;
  string action = 6;

  bool is_active = 7;

  string create_by = 12;
  string update_by = 13;

  google.protobuf.Timestamp create_date = 14;
  google.protobuf.Timestamp update_date = 15;
}

message PermissionMutateRequest {

  message Mutation {

    string op_id = 1 [
      (buf.validate.field).string.min_len = 1
    ];

    oneof action {
      Create create = 2;
      Update update = 3;
      Delete delete = 4;
    }

    message Create {

      option (auth.resource) = "PERMISSION";
      option (auth.action) = "CREATE";
      option (auth.require_tenant) = true;

      message Data {
        string code = 1 [
          (buf.validate.field).string.min_len = 1
        ];

        string name = 2 [
          (buf.validate.field).string.min_len = 1
        ];

        string description = 3;
      }

      Data data = 1 [
        (buf.validate.field).required = true
      ];
    }

    message Update {

      option (auth.resource) = "PERMISSION";
      option (auth.action) = "UPDATE";
      option (auth.resource_id_field) = "id";
      option (auth.require_tenant) = true;

      string id = 1 [
        (buf.validate.field).string.min_len = 1
      ];

      message Data {
        string name = 1;
        string description = 2;
      }

      Data data = 2 [
        (buf.validate.field).required = true
      ];
    }

    message Delete {

      option (auth.resource) = "PERMISSION";
      option (auth.action) = "DELETE";
      option (auth.resource_id_field) = "id";
      option (auth.require_tenant) = true;

      string id = 1 [
        (buf.validate.field).string.min_len = 1
      ];
    }
  }

  repeated Mutation mutations = 1 [
    (buf.validate.field).repeated.min_items = 1
  ];
}

  message PermissionMutationResult {
    oneof result {
      CreateResult create = 2;
      UpdateResult update = 3;
      DeleteResult delete = 4;
    }

    message CreateResult {
      string id = 1;
    }

    message UpdateResult {
      string id = 1;
    }

    message DeleteResult {
      string id = 1;
    }
  }



message PermissionViewRequest {}