// Code generated by generate_errors.sh. DO NOT EDIT.

package errors

import (
	"github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors"
)

var (
	VALIDATION_FAILED = apperrors.AppError{
		Key:           "VALIDATION_FAILED",
		Code:          "CORE-DOM-001",
		Domain:        "core",
		Layer:         "DOM",
		Component:     "validator",
		Tags:          []string{"domain","validation"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Validation failed",
		ClientMessage: "Validation failed",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	ENTITY_NOT_FOUND = apperrors.AppError{
		Key:           "ENTITY_NOT_FOUND",
		Code:          "CORE-DOM-002",
		Domain:        "core",
		Layer:         "DOM",
		Component:     "entity_domain",
		Tags:          []string{"domain"},
		Status:        404,
		GRPCCode:      "NotFound",
		Message:       "{{resource}} not found",
		ClientMessage: "{{resource}} not found",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	ENTITY_INVALID = apperrors.AppError{
		Key:           "ENTITY_INVALID",
		Code:          "AUTHZ-DOM-002",
		Domain:        "core",
		Layer:         "DOM",
		Component:     "entity_domain",
		Tags:          []string{"domain"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "{{resource}} contains invalid references",
		ClientMessage: "{{resource}} contains invalid references",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	MUTATE_OPERATION_UNSUPPORTED = apperrors.AppError{
		Key:           "MUTATE_OPERATION_UNSUPPORTED",
		Code:          "CORE-APP-001",
		Domain:        "core",
		Layer:         "APP",
		Component:     "mutate_engine",
		Tags:          []string{"application"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Unsupported mutate operation",
		ClientMessage: "Unsupported mutate operation",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	MUTATE_PARTIAL_FAILURE = apperrors.AppError{
		Key:           "MUTATE_PARTIAL_FAILURE",
		Code:          "CORE-APP-002",
		Domain:        "core",
		Layer:         "APP",
		Component:     "mutate_engine",
		Tags:          []string{"application"},
		Status:        200,
		GRPCCode:      "OK",
		Message:       "One or more operations failed",
		ClientMessage: "One or more operations failed",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	VIEW_OPERATION_UNSUPPORTED = apperrors.AppError{
		Key:           "VIEW_OPERATION_UNSUPPORTED",
		Code:          "CORE-APP-003",
		Domain:        "core",
		Layer:         "APP",
		Component:     "view_engine",
		Tags:          []string{"application"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Unsupported view operation",
		ClientMessage: "Unsupported view operation",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	VIEW_PARTIAL_FAILURE = apperrors.AppError{
		Key:           "VIEW_PARTIAL_FAILURE",
		Code:          "CORE-APP-004",
		Domain:        "core",
		Layer:         "APP",
		Component:     "view_engine",
		Tags:          []string{"application"},
		Status:        200,
		GRPCCode:      "OK",
		Message:       "One or more operations failed",
		ClientMessage: "One or more operations failed",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	APP_OPERATION_FAILED = apperrors.AppError{
		Key:           "APP_OPERATION_FAILED",
		Code:          "CORE-APP-005",
		Domain:        "core",
		Layer:         "APP",
		Component:     "application",
		Tags:          []string{"application"},
		Status:        500,
		GRPCCode:      "Internal",
		Message:       "Application operation failed",
		ClientMessage: "The operation could not be completed. Please try again later",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	ENTITY_ALREADY_EXISTS = apperrors.AppError{
		Key:           "ENTITY_ALREADY_EXISTS",
		Code:          "CORE-APP-006",
		Domain:        "core",
		Layer:         "APP",
		Component:     "entity_usecase",
		Tags:          []string{"application"},
		Status:        409,
		GRPCCode:      "AlreadyExists",
		Message:       "{{resource}} already exists",
		ClientMessage: "{{resource}} already exists",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	HANDLER_NOT_FOUND = apperrors.AppError{
		Key:           "HANDLER_NOT_FOUND",
		Code:          "CORE-APP-007",
		Domain:        "core",
		Layer:         "APP",
		Component:     "dispatcher",
		Tags:          []string{"application"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Handler not found",
		ClientMessage: "Handler not found",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	INVALID_COMMAND_TYPE = apperrors.AppError{
		Key:           "INVALID_COMMAND_TYPE",
		Code:          "CORE-APP-008",
		Domain:        "core",
		Layer:         "APP",
		Component:     "dispatcher",
		Tags:          []string{"application"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Invalid command type",
		ClientMessage: "Invalid command type",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	INVALID_REQUEST_PAYLOAD = apperrors.AppError{
		Key:           "INVALID_REQUEST_PAYLOAD",
		Code:          "CORE-TRANSPORT-001",
		Domain:        "core",
		Layer:         "TRANSPORT",
		Component:     "transport",
		Tags:          []string{"transport"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Invalid request payload",
		ClientMessage: "Invalid request payload",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	STRING_SPLIT_INVALID = apperrors.AppError{
		Key:           "STRING_SPLIT_INVALID",
		Code:          "CORE-PARSE-001",
		Domain:        "core",
		Layer:         "PARSE",
		Component:     "parser",
		Tags:          []string{"parser"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Invalid string format",
		ClientMessage: "Invalid string format",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	UUID_INVALID = apperrors.AppError{
		Key:           "UUID_INVALID",
		Code:          "CORE-PARSE-002",
		Domain:        "core",
		Layer:         "PARSE",
		Component:     "parser",
		Tags:          []string{"parser"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Invalid UUID format",
		ClientMessage: "Invalid UUID format",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	MUTATE_PARSE_FAILED = apperrors.AppError{
		Key:           "MUTATE_PARSE_FAILED",
		Code:          "CORE-PARSE-003",
		Domain:        "core",
		Layer:         "PARSE",
		Component:     "mutate_engine",
		Tags:          []string{"parser"},
		Status:        400,
		GRPCCode:      "InvalidArgument",
		Message:       "Failed to parse mutation payload",
		ClientMessage: "Failed to parse mutation payload",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

	JSON_SERIALIZATION_FAILED = apperrors.AppError{
		Key:           "JSON_SERIALIZATION_FAILED",
		Code:          "CORE-SERIALIZER-001",
		Domain:        "core",
		Layer:         "SERIALIZER",
		Component:     "json",
		Tags:          []string{"serializer","json"},
		Status:        500,
		GRPCCode:      "Internal",
		Message:       "Failed to serialize payload",
		ClientMessage: "The request could not be processed",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	JSON_DESERIALIZATION_FAILED = apperrors.AppError{
		Key:           "JSON_DESERIALIZATION_FAILED",
		Code:          "CORE-SERIALIZER-002",
		Domain:        "core",
		Layer:         "SERIALIZER",
		Component:     "json",
		Tags:          []string{"serializer","json"},
		Status:        500,
		GRPCCode:      "Internal",
		Message:       "Failed to deserialize payload",
		ClientMessage: "The request could not be processed",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	NIL = apperrors.AppError{
		Key:           "NIL",
		Code:          "CORE-INFRA-001",
		Domain:        "core",
		Layer:         "INFRA",
		Component:     "nil",
		Tags:          []string{"nil","nil"},
		Status:        500,
		GRPCCode:      "Nil",
		Message:       "Nil",
		ClientMessage: "Nil",
		Severity:      "S2",
		Retryable:     false,
		Cause:         "",
	}

	INTERNAL_ERROR = apperrors.AppError{
		Key:           "INTERNAL_ERROR",
		Code:          "CORE-SYS-001",
		Domain:        "core",
		Layer:         "SYS",
		Component:     "system",
		Tags:          []string{"system"},
		Status:        500,
		GRPCCode:      "Internal",
		Message:       "Internal server error",
		ClientMessage: "Something went wrong. Please try again later",
		Severity:      "S1",
		Retryable:     false,
		Cause:         "",
	}

	REQUEST_CANCELED = apperrors.AppError{
		Key:           "REQUEST_CANCELED",
		Code:          "CORE-SYS-002",
		Domain:        "core",
		Layer:         "SYS",
		Component:     "system",
		Tags:          []string{"system","lifecycle"},
		Status:        499,
		GRPCCode:      "Canceled",
		Message:       "Request canceled",
		ClientMessage: "Request canceled",
		Severity:      "S3",
		Retryable:     false,
		Cause:         "",
	}

)

var (
	REASON_VAL_REQUIRED = apperrors.Violation{
		Code:    "VAL_REQUIRED",
		Message: "Field is required",
	}

	REASON_VAL_NULL = apperrors.Violation{
		Code:    "VAL_NULL",
		Message: "Field must not be null",
	}

	REASON_VAL_INVALID_FORMAT = apperrors.Violation{
		Code:    "VAL_INVALID_FORMAT",
		Message: "Invalid format",
	}

	REASON_VAL_INVALID_TYPE = apperrors.Violation{
		Code:    "VAL_INVALID_TYPE",
		Message: "Invalid data type",
	}

	REASON_VAL_INVALID_ENUM = apperrors.Violation{
		Code:    "VAL_INVALID_ENUM",
		Message: "Invalid enum value",
	}

	REASON_VAL_OUT_OF_RANGE = apperrors.Violation{
		Code:    "VAL_OUT_OF_RANGE",
		Message: "Out of range",
	}

	REASON_VAL_TOO_SHORT = apperrors.Violation{
		Code:    "VAL_TOO_SHORT",
		Message: "Value is too short",
	}

	REASON_VAL_TOO_LONG = apperrors.Violation{
		Code:    "VAL_TOO_LONG",
		Message: "Value is too long",
	}

	REASON_APP_DUPLICATE = apperrors.Violation{
		Code:    "APP_DUPLICATE",
		Message: "Duplicate value",
	}

	REASON_APP_CONFLICT = apperrors.Violation{
		Code:    "APP_CONFLICT",
		Message: "Value conflicts with existing data",
	}

	REASON_APP_NOT_ALLOWED = apperrors.Violation{
		Code:    "APP_NOT_ALLOWED",
		Message: "Operation not allowed",
	}

	REASON_APP_FORBIDDEN_STATE = apperrors.Violation{
		Code:    "APP_FORBIDDEN_STATE",
		Message: "Invalid state for operation",
	}

	REASON_APP_NOT_FOUND = apperrors.Violation{
		Code:    "APP_NOT_FOUND",
		Message: "Not found",
	}

	REASON_APP_ALREADY_EXISTS = apperrors.Violation{
		Code:    "APP_ALREADY_EXISTS",
		Message: "Already exists",
	}

	REASON_PARSE_INVALID_REFERENCE = apperrors.Violation{
		Code:    "PARSE_INVALID_REFERENCE",
		Message: "Invalid reference",
	}

	REASON_PARSE_INVALID_TIME_RANGE = apperrors.Violation{
		Code:    "PARSE_INVALID_TIME_RANGE",
		Message: "Invalid time range",
	}

	REASON_SEC_UNSAFE_INPUT = apperrors.Violation{
		Code:    "SEC_UNSAFE_INPUT",
		Message: "Unsafe input detected",
	}

	REASON_SEC_INVALID = apperrors.Violation{
		Code:    "SEC_INVALID",
		Message: "Invalid value",
	}

)

var ErrorByCode = map[string]apperrors.AppError{
	"CORE-DOM-001": VALIDATION_FAILED,
	"CORE-DOM-002": ENTITY_NOT_FOUND,
	"AUTHZ-DOM-002": ENTITY_INVALID,
	"CORE-APP-001": MUTATE_OPERATION_UNSUPPORTED,
	"CORE-APP-002": MUTATE_PARTIAL_FAILURE,
	"CORE-APP-003": VIEW_OPERATION_UNSUPPORTED,
	"CORE-APP-004": VIEW_PARTIAL_FAILURE,
	"CORE-APP-005": APP_OPERATION_FAILED,
	"CORE-APP-006": ENTITY_ALREADY_EXISTS,
	"CORE-APP-007": HANDLER_NOT_FOUND,
	"CORE-APP-008": INVALID_COMMAND_TYPE,
	"CORE-TRANSPORT-001": INVALID_REQUEST_PAYLOAD,
	"CORE-PARSE-001": STRING_SPLIT_INVALID,
	"CORE-PARSE-002": UUID_INVALID,
	"CORE-PARSE-003": MUTATE_PARSE_FAILED,
	"CORE-SERIALIZER-001": JSON_SERIALIZATION_FAILED,
	"CORE-SERIALIZER-002": JSON_DESERIALIZATION_FAILED,
	"CORE-INFRA-001": NIL,
	"CORE-SYS-001": INTERNAL_ERROR,
	"CORE-SYS-002": REQUEST_CANCELED,
}

var ErrorDetailByCode = map[string]apperrors.Violation{
	"VAL_REQUIRED": REASON_VAL_REQUIRED,
	"VAL_NULL": REASON_VAL_NULL,
	"VAL_INVALID_FORMAT": REASON_VAL_INVALID_FORMAT,
	"VAL_INVALID_TYPE": REASON_VAL_INVALID_TYPE,
	"VAL_INVALID_ENUM": REASON_VAL_INVALID_ENUM,
	"VAL_OUT_OF_RANGE": REASON_VAL_OUT_OF_RANGE,
	"VAL_TOO_SHORT": REASON_VAL_TOO_SHORT,
	"VAL_TOO_LONG": REASON_VAL_TOO_LONG,
	"APP_DUPLICATE": REASON_APP_DUPLICATE,
	"APP_CONFLICT": REASON_APP_CONFLICT,
	"APP_NOT_ALLOWED": REASON_APP_NOT_ALLOWED,
	"APP_FORBIDDEN_STATE": REASON_APP_FORBIDDEN_STATE,
	"APP_NOT_FOUND": REASON_APP_NOT_FOUND,
	"APP_ALREADY_EXISTS": REASON_APP_ALREADY_EXISTS,
	"PARSE_INVALID_REFERENCE": REASON_PARSE_INVALID_REFERENCE,
	"PARSE_INVALID_TIME_RANGE": REASON_PARSE_INVALID_TIME_RANGE,
	"SEC_UNSAFE_INPUT": REASON_SEC_UNSAFE_INPUT,
	"SEC_INVALID": REASON_SEC_INVALID,
}

