// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "github.com/vokhanh12/refactor-rongstore-system/server/internal/platform/apperrors"

var (
	LOGIN_EMAIL_EMPTY = apperrors.AppError{
		Key: "LOGIN_EMAIL_EMPTY",
		Code: "AUTH-VAL-001",
		Component: "validator",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Email is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_EMAIL_INVALID = apperrors.AppError{
		Key: "LOGIN_EMAIL_INVALID",
		Code: "AUTH-VAL-002",
		Component: "validator",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid email format",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_PASSWORD_EMPTY = apperrors.AppError{
		Key: "LOGIN_PASSWORD_EMPTY",
		Code: "AUTH-VAL-003",
		Component: "validator",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Password is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_PAYLOAD_INVALID = apperrors.AppError{
		Key: "LOGIN_PAYLOAD_INVALID",
		Code: "AUTH-VAL-004",
		Component: "validator",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid request payload",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	TOKEN_EXPIRED = apperrors.AppError{
		Key: "TOKEN_EXPIRED",
		Code: "AUTH-SEC-001",
		Component: "jwt",
		Tags: []string{"security","auth"},
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Token expired",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	UNAUTHORIZED = apperrors.AppError{
		Key: "UNAUTHORIZED",
		Code: "AUTH-SEC-002",
		Component: "auth_service",
		Tags: []string{"security","auth"},
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Authentication required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

)

// ErrorByCode maps error codes to AppError
var ErrorByCode = map[string]apperrors.AppError{
	"AUTH-VAL-001": LOGIN_EMAIL_EMPTY,
	"AUTH-VAL-002": LOGIN_EMAIL_INVALID,
	"AUTH-VAL-003": LOGIN_PASSWORD_EMPTY,
	"AUTH-VAL-004": LOGIN_PAYLOAD_INVALID,
	"AUTH-SEC-001": TOKEN_EXPIRED,
	"AUTH-SEC-002": UNAUTHORIZED,
}

