-- +goose Up
-- +goose StatementBegin

CREATE TABLE IDEMPOTENCY_RECORDS (
    ID UUID PRIMARY KEY,
    KEY TEXT UNIQUE NOT NULL,
    REQUEST TEXT NOT NULL,
    RESPONSE TEXT NOT NULL,
    STATUS_CODE INTEGER NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IDX_IDEMPOTENCT_key ON IDEMPOTENCT_RECORDS(key);

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS IDEMPOTENCY_RECORDS;
-- +goose StatementEnd