// Code generated by generate_errors.sh. DO NOT EDIT.

package errors

import "github.com/vokhanh12/refactor-rongstore-system/server/internal/platform/apperrors"

var (
	DB_TIMEOUT = apperrors.AppError{
		Key:          "DB_TIMEOUT",
		Code:         "PLATFORM-INFRA-001",
		Layer:        "INFRA",
		Component:    "postgres",
		Tags:         []string{"infra", "database"},
		Status:       503,
		GRPCCode:     "Unavailable",
		Message:      "Database timeout",
		Severity:     "S1",
		Retryable:    true,
		Cause:        "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_QUERY_FAILED = apperrors.AppError{
		Key:          "DB_QUERY_FAILED",
		Code:         "PLATFORM-INFRA-002",
		Layer:        "INFRA",
		Component:    "postgres",
		Tags:         []string{"infra", "database"},
		Status:       500,
		GRPCCode:     "Internal",
		Message:      "Database query failed",
		Severity:     "S2",
		Retryable:    false,
		Cause:        "",
		ClientAction: "",
		ServerAction: "",
	}

	REDIS_UNAVAILABLE = apperrors.AppError{
		Key:          "REDIS_UNAVAILABLE",
		Code:         "PLATFORM-INFRA-003",
		Layer:        "INFRA",
		Component:    "redis",
		Tags:         []string{"infra", "cache"},
		Status:       503,
		GRPCCode:     "Unavailable",
		Message:      "Redis unavailable",
		Severity:     "S1",
		Retryable:    true,
		Cause:        "",
		ClientAction: "",
		ServerAction: "",
	}

	EXTERNAL_SERVICE_UNAVAILABLE = apperrors.AppError{
		Key:          "EXTERNAL_SERVICE_UNAVAILABLE",
		Code:         "PLATFORM-INFRA-004",
		Layer:        "INFRA",
		Component:    "external_service",
		Tags:         []string{"infra", "external"},
		Status:       503,
		GRPCCode:     "Unavailable",
		Message:      "External service unavailable",
		Severity:     "S1",
		Retryable:    true,
		Cause:        "",
		ClientAction: "",
		ServerAction: "",
	}

	POSTGRES_UNAVAILABLE = apperrors.AppError{
		Key:          "POSTGRES_UNAVAILABLE",
		Code:         "PLATFORM-INFRA-005",
		Layer:        "INFRA",
		Component:    "postgres",
		Tags:         []string{"infra", "database"},
		Status:       503,
		GRPCCode:     "Unavailable",
		Message:      "Postgres unavailable",
		Severity:     "S1",
		Retryable:    true,
		Cause:        "",
		ClientAction: "",
		ServerAction: "",
	}
)

var (
	REASON_VAL_REQUIRED = apperrors.AppErrorDetail{
		Code:    "VAL_REQUIRED",
		Message: "Field is required",
	}

	REASON_VAL_NULL = apperrors.AppErrorDetail{
		Code:    "VAL_NULL",
		Message: "Field must not be null",
	}

	REASON_VAL_INVALID_FORMAT = apperrors.AppErrorDetail{
		Code:    "VAL_INVALID_FORMAT",
		Message: "Invalid format",
	}

	REASON_VAL_INVALID_TYPE = apperrors.AppErrorDetail{
		Code:    "VAL_INVALID_TYPE",
		Message: "Invalid data type",
	}

	REASON_VAL_INVALID_ENUM = apperrors.AppErrorDetail{
		Code:    "VAL_INVALID_ENUM",
		Message: "Invalid enum value",
	}

	REASON_VAL_OUT_OF_RANGE = apperrors.AppErrorDetail{
		Code:    "VAL_OUT_OF_RANGE",
		Message: "Out of range",
	}

	REASON_VAL_TOO_SHORT = apperrors.AppErrorDetail{
		Code:    "VAL_TOO_SHORT",
		Message: "Value is too short",
	}

	REASON_VAL_TOO_LONG = apperrors.AppErrorDetail{
		Code:    "VAL_TOO_LONG",
		Message: "Value is too long",
	}

	REASON_VAL_MIN = apperrors.AppErrorDetail{
		Code:    "VAL_MIN",
		Message: "Value is below minimum",
	}

	REASON_VAL_MAX = apperrors.AppErrorDetail{
		Code:    "VAL_MAX",
		Message: "Value exceeds maximum",
	}

	REASON_VAL_INVALID_PATTERN = apperrors.AppErrorDetail{
		Code:    "VAL_INVALID_PATTERN",
		Message: "Value does not match required pattern",
	}

	REASON_APP_DUPLICATE = apperrors.AppErrorDetail{
		Code:    "APP_DUPLICATE",
		Message: "Duplicate value",
	}

	REASON_APP_CONFLICT = apperrors.AppErrorDetail{
		Code:    "APP_CONFLICT",
		Message: "Value conflicts with existing data",
	}

	REASON_APP_NOT_ALLOWED = apperrors.AppErrorDetail{
		Code:    "APP_NOT_ALLOWED",
		Message: "Operation not allowed",
	}

	REASON_APP_FORBIDDEN_STATE = apperrors.AppErrorDetail{
		Code:    "APP_FORBIDDEN_STATE",
		Message: "Invalid state for operation",
	}

	REASON_APP_NOT_FOUND = apperrors.AppErrorDetail{
		Code:    "APP_NOT_FOUND",
		Message: "Not found",
	}

	REASON_APP_ALREADY_EXISTS = apperrors.AppErrorDetail{
		Code:    "APP_ALREADY_EXISTS",
		Message: "Already exists",
	}

	REASON_APP_DEPENDENCY_MISSING = apperrors.AppErrorDetail{
		Code:    "APP_DEPENDENCY_MISSING",
		Message: "Required dependency is missing",
	}

	REASON_PARSE_INVALID_REFERENCE = apperrors.AppErrorDetail{
		Code:    "PARSE_INVALID_REFERENCE",
		Message: "Invalid reference",
	}

	REASON_PARSE_INVALID_TIME_RANGE = apperrors.AppErrorDetail{
		Code:    "PARSE_INVALID_TIME_RANGE",
		Message: "Invalid time range",
	}

	REASON_SEC_UNSAFE_INPUT = apperrors.AppErrorDetail{
		Code:    "SEC_UNSAFE_INPUT",
		Message: "Unsafe input detected",
	}

	REASON_SEC_INVALID = apperrors.AppErrorDetail{
		Code:    "SEC_INVALID",
		Message: "Invalid value",
	}
)

var ErrorByCode = map[string]apperrors.AppError{
	"PLATFORM-INFRA-001": DB_TIMEOUT,
	"PLATFORM-INFRA-002": DB_QUERY_FAILED,
	"PLATFORM-INFRA-003": REDIS_UNAVAILABLE,
	"PLATFORM-INFRA-004": EXTERNAL_SERVICE_UNAVAILABLE,
	"PLATFORM-INFRA-005": POSTGRES_UNAVAILABLE,
}

var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{
	"VAL_REQUIRED":             REASON_VAL_REQUIRED,
	"VAL_NULL":                 REASON_VAL_NULL,
	"VAL_INVALID_FORMAT":       REASON_VAL_INVALID_FORMAT,
	"VAL_INVALID_TYPE":         REASON_VAL_INVALID_TYPE,
	"VAL_INVALID_ENUM":         REASON_VAL_INVALID_ENUM,
	"VAL_OUT_OF_RANGE":         REASON_VAL_OUT_OF_RANGE,
	"VAL_TOO_SHORT":            REASON_VAL_TOO_SHORT,
	"VAL_TOO_LONG":             REASON_VAL_TOO_LONG,
	"VAL_MIN":                  REASON_VAL_MIN,
	"VAL_MAX":                  REASON_VAL_MAX,
	"VAL_INVALID_PATTERN":      REASON_VAL_INVALID_PATTERN,
	"APP_DUPLICATE":            REASON_APP_DUPLICATE,
	"APP_CONFLICT":             REASON_APP_CONFLICT,
	"APP_NOT_ALLOWED":          REASON_APP_NOT_ALLOWED,
	"APP_FORBIDDEN_STATE":      REASON_APP_FORBIDDEN_STATE,
	"APP_NOT_FOUND":            REASON_APP_NOT_FOUND,
	"APP_ALREADY_EXISTS":       REASON_APP_ALREADY_EXISTS,
	"APP_DEPENDENCY_MISSING":   REASON_APP_DEPENDENCY_MISSING,
	"PARSE_INVALID_REFERENCE":  REASON_PARSE_INVALID_REFERENCE,
	"PARSE_INVALID_TIME_RANGE": REASON_PARSE_INVALID_TIME_RANGE,
	"SEC_UNSAFE_INPUT":         REASON_SEC_UNSAFE_INPUT,
	"SEC_INVALID":              REASON_SEC_INVALID,
}
