// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors"

var (
	DB_TIMEOUT = apperrors.AppError{
		Key: "DB_TIMEOUT",
		Code: "PLATFORM-INF-001",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Database timeout",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_QUERY_FAILED = apperrors.AppError{
		Key: "DB_QUERY_FAILED",
		Code: "PLATFORM-INF-002",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Database query failed",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	REDIS_UNAVAILABLE = apperrors.AppError{
		Key: "REDIS_UNAVAILABLE",
		Code: "PLATFORM-INF-003",
		Component: "redis",
		Tags: []string{"infra","cache"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Redis unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	EXTERNAL_SERVICE_UNAVAILABLE = apperrors.AppError{
		Key: "EXTERNAL_SERVICE_UNAVAILABLE",
		Code: "PLATFORM-INF-004",
		Component: "external_service",
		Tags: []string{"infra","external"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "External service unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

)

// ErrorByCode maps error codes to AppError
var ErrorByCode = map[string]apperrors.AppError{
	"PLATFORM-INF-001": DB_TIMEOUT,
	"PLATFORM-INF-002": DB_QUERY_FAILED,
	"PLATFORM-INF-003": REDIS_UNAVAILABLE,
	"PLATFORM-INF-004": EXTERNAL_SERVICE_UNAVAILABLE,
}

