// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package iam_sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Permission struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Resource    string         `json:"resource"`
	Action      string         `json:"action"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdatedBy   uuid.NullUUID  `json:"updated_by"`
}

type Role struct {
	ID          uuid.UUID      `json:"id"`
	Code        string         `json:"code"`
	Name        sql.NullString `json:"name"`
	Type        string         `json:"type"`
	Description sql.NullString `json:"description"`
	IsSystem    sql.NullBool   `json:"is_system"`
	IsSuper     sql.NullBool   `json:"is_super"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	CreatedBy   uuid.NullUUID  `json:"created_by"`
	UpdatedBy   uuid.NullUUID  `json:"updated_by"`
}

type RoleAssignement struct {
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	ScopeID    uuid.UUID     `json:"scope_id"`
	ScopeType  string        `json:"scope_type"`
	AssignedAt sql.NullTime  `json:"assigned_at"`
	AssignedBy uuid.NullUUID `json:"assigned_by"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
	CreatedBy  uuid.NullUUID `json:"created_by"`
	UpdatedBy  uuid.NullUUID `json:"updated_by"`
}

type RolePermission struct {
	RoleID       uuid.UUID     `json:"role_id"`
	PermissionID uuid.UUID     `json:"permission_id"`
	GrantedAt    sql.NullTime  `json:"granted_at"`
	GrantedBy    uuid.NullUUID `json:"granted_by"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	UpdatedAt    sql.NullTime  `json:"updated_at"`
	CreatedBy    uuid.NullUUID `json:"created_by"`
	UpdatedBy    uuid.NullUUID `json:"updated_by"`
}
