// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package iam_sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type PermissionAccessScope string

const (
	PermissionAccessScopeALL PermissionAccessScope = "ALL"
	PermissionAccessScopeOWN PermissionAccessScope = "OWN"
)

func (e *PermissionAccessScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermissionAccessScope(s)
	case string:
		*e = PermissionAccessScope(s)
	default:
		return fmt.Errorf("unsupported scan type for PermissionAccessScope: %T", src)
	}
	return nil
}

type NullPermissionAccessScope struct {
	PermissionAccessScope PermissionAccessScope `json:"permission_access_scope"`
	Valid                 bool                  `json:"valid"` // Valid is true if PermissionAccessScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermissionAccessScope) Scan(value interface{}) error {
	if value == nil {
		ns.PermissionAccessScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermissionAccessScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermissionAccessScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermissionAccessScope), nil
}

type RoleScopeType string

const (
	RoleScopeTypeGLOBAL RoleScopeType = "GLOBAL"
	RoleScopeTypeTENANT RoleScopeType = "TENANT"
	RoleScopeTypeUNIT   RoleScopeType = "UNIT"
)

func (e *RoleScopeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleScopeType(s)
	case string:
		*e = RoleScopeType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleScopeType: %T", src)
	}
	return nil
}

type NullRoleScopeType struct {
	RoleScopeType RoleScopeType `json:"role_scope_type"`
	Valid         bool          `json:"valid"` // Valid is true if RoleScopeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleScopeType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleScopeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleScopeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleScopeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleScopeType), nil
}

type Permission struct {
	ID          uuid.UUID  `json:"id"`
	Code        string     `json:"code"`
	Name        string     `json:"name"`
	Description *string    `json:"description"`
	Resource    string     `json:"resource"`
	Action      string     `json:"action"`
	IsActive    bool       `json:"is_active"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

type Role struct {
	ID          uuid.UUID  `json:"id"`
	Code        string     `json:"code"`
	Name        string     `json:"name"`
	Level       int32      `json:"level"`
	Description *string    `json:"description"`
	IsSystem    bool       `json:"is_system"`
	IsActive    bool       `json:"is_active"`
	IsSuper     bool       `json:"is_super"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	CreatedBy   *uuid.UUID `json:"created_by"`
	UpdatedBy   *uuid.UUID `json:"updated_by"`
}

type RoleAssignment struct {
	ID         uuid.UUID     `json:"id"`
	UserID     uuid.UUID     `json:"user_id"`
	RoleID     uuid.UUID     `json:"role_id"`
	ScopeID    *uuid.UUID    `json:"scope_id"`
	ScopeType  RoleScopeType `json:"scope_type"`
	AssignedAt time.Time     `json:"assigned_at"`
	AssignedBy *uuid.UUID    `json:"assigned_by"`
	CreatedAt  time.Time     `json:"created_at"`
	UpdatedAt  time.Time     `json:"updated_at"`
	CreatedBy  *uuid.UUID    `json:"created_by"`
	UpdatedBy  *uuid.UUID    `json:"updated_by"`
}

type RolePermission struct {
	RoleID       uuid.UUID             `json:"role_id"`
	PermissionID uuid.UUID             `json:"permission_id"`
	AccessScope  PermissionAccessScope `json:"access_scope"`
	GrantedAt    time.Time             `json:"granted_at"`
	GrantedBy    *uuid.UUID            `json:"granted_by"`
	CreatedAt    time.Time             `json:"created_at"`
	UpdatedAt    time.Time             `json:"updated_at"`
	CreatedBy    *uuid.UUID            `json:"created_by"`
	UpdatedBy    *uuid.UUID            `json:"updated_by"`
}
