// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: PERMISSIONS.sql

package iam_sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT ID, CODE, NAME, RESOURCE, ACTION
FROM PERMISSIONS
WHERE code = $1
`

type GetPermissionByCodeRow struct {
	ID       uuid.UUID      `json:"id"`
	Code     string         `json:"code"`
	Name     sql.NullString `json:"name"`
	Resource string         `json:"resource"`
	Action   string         `json:"action"`
}

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByCode, code)
	var i GetPermissionByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Resource,
		&i.Action,
	)
	return i, err
}
