// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package iam_sqlc

import (
	"context"
)

type Querier interface {
	CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error)
	GetPermissionByCode(ctx context.Context, code string) (GetPermissionByCodeRow, error)
	GetRolePermissionsByRoleRefs(ctx context.Context, dollar_1 []byte) ([]GetRolePermissionsByRoleRefsRow, error)
}

var _ Querier = (*Queries)(nil)
