// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package iam_sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetRoleScopesByUserID(ctx context.Context, userID uuid.UUID) ([]GetRoleScopesByUserIDRow, error)
}

var _ Querier = (*Queries)(nil)
