// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ROLES.sql

package iam_sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id,
    scope_id,
    role_scope_type,
    code,
    name,
    description,
    role_access_scope,
    level,
    is_system,
    is_active,
    is_super
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING 
    id,
    scope_id,
    role_scope_type,
    code,
    name,
    description,
    role_access_scope,
    level,
    is_system,
    is_active,
    is_super
`

type CreateRoleParams struct {
	ID              uuid.UUID       `json:"id"`
	ScopeID         pgtype.UUID     `json:"scope_id"`
	RoleScopeType   RoleScopeType   `json:"role_scope_type"`
	Code            string          `json:"code"`
	Name            string          `json:"name"`
	Description     pgtype.Text     `json:"description"`
	RoleAccessScope RoleAccessScope `json:"role_access_scope"`
	Level           pgtype.Int4     `json:"level"`
	IsSystem        bool            `json:"is_system"`
	IsActive        bool            `json:"is_active"`
	IsSuper         bool            `json:"is_super"`
}

type CreateRoleRow struct {
	ID              uuid.UUID       `json:"id"`
	ScopeID         pgtype.UUID     `json:"scope_id"`
	RoleScopeType   RoleScopeType   `json:"role_scope_type"`
	Code            string          `json:"code"`
	Name            string          `json:"name"`
	Description     pgtype.Text     `json:"description"`
	RoleAccessScope RoleAccessScope `json:"role_access_scope"`
	Level           pgtype.Int4     `json:"level"`
	IsSystem        bool            `json:"is_system"`
	IsActive        bool            `json:"is_active"`
	IsSuper         bool            `json:"is_super"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (CreateRoleRow, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.ScopeID,
		arg.RoleScopeType,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.RoleAccessScope,
		arg.Level,
		arg.IsSystem,
		arg.IsActive,
		arg.IsSuper,
	)
	var i CreateRoleRow
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.RoleScopeType,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.RoleAccessScope,
		&i.Level,
		&i.IsSystem,
		&i.IsActive,
		&i.IsSuper,
	)
	return i, err
}
