// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ROLE_ASIGNEMENT.sql

package iam_sqlc

import (
	"context"

	"github.com/google/uuid"
)

const ListRoleScopes = `-- name: ListRoleScopes :many
SELECT
    role_id,
    scope_id,
    scope_type
FROM ROLE_ASSIGNMENTS
WHERE user_id = $1
`

type ListRoleScopesRow struct {
	RoleID    uuid.UUID     `json:"role_id"`
	ScopeID   *uuid.UUID    `json:"scope_id"`
	ScopeType RoleScopeType `json:"scope_type"`
}

func (q *Queries) ListRoleScopes(ctx context.Context, userID uuid.UUID) ([]ListRoleScopesRow, error) {
	rows, err := q.db.Query(ctx, ListRoleScopes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoleScopesRow
	for rows.Next() {
		var i ListRoleScopesRow
		if err := rows.Scan(&i.RoleID, &i.ScopeID, &i.ScopeType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
