// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ROLE_ASIGNEMENT.sql

package iam_sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getRoleScopesByUserID = `-- name: GetRoleScopesByUserID :many
SELECT
    role_id,
    scope_id,
    scope_type
FROM ROLE_ASSIGNMENTS
WHERE user_id = $1
`

type GetRoleScopesByUserIDRow struct {
	RoleID    uuid.UUID     `json:"role_id"`
	ScopeID   *uuid.UUID    `json:"scope_id"`
	ScopeType RoleScopeType `json:"scope_type"`
}

func (q *Queries) GetRoleScopesByUserID(ctx context.Context, userID uuid.UUID) ([]GetRoleScopesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getRoleScopesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleScopesByUserIDRow
	for rows.Next() {
		var i GetRoleScopesByUserIDRow
		if err := rows.Scan(&i.RoleID, &i.ScopeID, &i.ScopeType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
