// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ROLE_PERMISSION.sql

package iam_sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAuthorizationGrantsByRoleRefs = `-- name: ListAuthorizationGrantsByRoleRefs :many
SELECT
    r.code AS role_code,
    r.scope_id AS role_scope_id,
    r.is_super AS role_is_super,

    p.resource AS permission_resource,
    p.action AS permission_action

FROM roles r

JOIN role_permissions rp
    ON rp.role_id = r.id

JOIN permissions p
    ON p.id = rp.permission_id

JOIN jsonb_to_recordset($1::jsonb)
    AS x(role_code text, scope_id uuid)

ON r.code = x.role_code

AND (
    r.scope_id = x.scope_id
    OR (r.scope_id IS NULL AND x.scope_id IS NULL)
)
`

type ListAuthorizationGrantsByRoleRefsRow struct {
	RoleCode           string      `json:"role_code"`
	RoleScopeID        pgtype.UUID `json:"role_scope_id"`
	RoleIsSuper        bool        `json:"role_is_super"`
	PermissionResource string      `json:"permission_resource"`
	PermissionAction   string      `json:"permission_action"`
}

func (q *Queries) ListAuthorizationGrantsByRoleRefs(ctx context.Context, dollar_1 []byte) ([]ListAuthorizationGrantsByRoleRefsRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizationGrantsByRoleRefs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizationGrantsByRoleRefsRow
	for rows.Next() {
		var i ListAuthorizationGrantsByRoleRefsRow
		if err := rows.Scan(
			&i.RoleCode,
			&i.RoleScopeID,
			&i.RoleIsSuper,
			&i.PermissionResource,
			&i.PermissionAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
