-- 001_PERMISSION.sql

-- +goose Up

-- +goose StatementBegin

CREATE TABLE PERMISSIONS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    CODE VARCHAR(150) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,

    RESOURCE VARCHAR(100) NOT NULL,
    ACTION VARCHAR(50) NOT NULL,

    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CREATED_BY UUID,
    UPDATED_BY UUID,

    CONSTRAINT UQ_PERMISSIONS_CODE
        UNIQUE (CODE),

    CONSTRAINT UQ_PERMISSIONS_RESOURCE_ACTION
        UNIQUE (RESOURCE, ACTION)
);

CREATE INDEX IDX_PERMISSIONS_RESOURCE
    ON PERMISSIONS (RESOURCE);

-- +goose StatementEnd


-- +goose Down

-- +goose StatementBegin

DROP TABLE IF EXISTS PERMISSIONS;

-- +goose StatementEnd