-- +goose Up
-- +goose StatementBegin

CREATE TABLE PERMISSIONS (
  ID UUID PRIMARY KEY,
  CODE VARCHAR(150) UNIQUE NOT NULL,

  NAME VARCHAR(255),
  DESCRIPTION TEXT,

  RESOURCE VARCHAR(100) NOT NULL,
  ACTION VARCHAR(50) NOT NULL,

  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  CONSTRAINT UQ_PERMISSION_RESOURCE_ACTION
    UNIQUE (RESOURCE, ACTION)
);

CREATE INDEX IDX_PERMISSION_RESOURCE
ON PERMISSIONS(RESOURCE);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS PERMISSIONS;

-- +goose StatementEnd