-- +goose Up
-- +goose StatementBegin

CREATE TYPE SCOPE_TYPE AS ENUM ('GLOBAL', 'TENANT', 'UNIT');
CREATE TYPE ACCESS_SCOPE AS ENUM ('ALL', 'OWN');

CREATE TABLE ROLES (
  ID UUID PRIMARY KEY,

  SCOPE_TYPE SCOPE_TYPE NOT NULL,
  SCOPE_ID UUID,

  CODE VARCHAR(100) NOT NULL,
  NAME VARCHAR(255),
  DESCRIPTION TEXT,

  ACCESS_SCOPE ACCESS_SCOPE DEFAULT 'ALL',
  LEVEL INT DEFAULT 0,

  IS_SYSTEM BOOLEAN DEFAULT FALSE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,

  CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  CONSTRAINT UQ_ROLES_CODE_SCOPE 
    UNIQUE (CODE, SCOPE_TYPE, SCOPE_ID),

  CONSTRAINT CK_ROLES_SCOPE_VALID
    CHECK (
      (SCOPE_TYPE = 'GLOBAL' AND SCOPE_ID IS NULL) OR
      (SCOPE_TYPE IN ('TENANT', 'UNIT') AND SCOPE_ID IS NOT NULL)
    )
);

CREATE INDEX IDX_ROLES_SCOPE 
ON ROLES (SCOPE_TYPE, SCOPE_ID);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS ROLES;
DROP TYPE IF EXISTS ACCESS_SCOPE;
DROP TYPE IF EXISTS SCOPE_TYPE;

-- +goose StatementEnd