-- 002_ROLES.sql

-- +goose Up

-- +goose StatementBegin

CREATE TABLE ROLES (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    CODE VARCHAR(100) NOT NULL,
    NAME VARCHAR(255) NOT NULL,

    LEVEL INT NOT NULL DEFAULT 0,

    DESCRIPTION TEXT,

    IS_SYSTEM BOOLEAN NOT NULL DEFAULT FALSE,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,

    IS_SUPER BOOLEAN NOT NULL DEFAULT FALSE,

    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CREATED_BY UUID,
    UPDATED_BY UUID,

    CONSTRAINT UQ_ROLES_CODE
        UNIQUE (CODE),

    CONSTRAINT CK_ROLES_LEVEL
        CHECK (LEVEL >= 0)
);

CREATE INDEX IDX_ROLES_ACTIVE
    ON ROLES (IS_ACTIVE);

-- +goose StatementEnd


-- +goose Down

-- +goose StatementBegin

DROP TABLE IF EXISTS ROLES;

-- +goose StatementEnd