-- +goose Up
-- +goose StatementBegin

CREATE TYPE ROLE_SCOPE_TYPE AS ENUM ('GLOBAL', 'TENANT', 'UNIT');
CREATE TYPE ROLE_ACCESS_SCOPE AS ENUM ('ALL', 'OWN');

CREATE TABLE ROLES (
  ID UUID PRIMARY KEY,
  SCOPE_ID UUID,

  ROLE_SCOPE_TYPE ROLE_SCOPE_TYPE NOT NULL,

  CODE VARCHAR(100) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  DESCRIPTION TEXT,

  ROLE_ACCESS_SCOPE ROLE_ACCESS_SCOPE NOT NULL DEFAULT 'ALL',
  LEVEL INT NOT NULL DEFAULT 0,

  IS_SYSTEM BOOLEAN NOT NULL DEFAULT FALSE,
  IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
  IS_SUPER BOOLEAN NOT NULL DEFAULT TRUE,

  CREATED_AT TIMESTAMPTZ DEFAULT NOW(),
  UPDATED_AT TIMESTAMPTZ DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  CONSTRAINT UQ_ROLES_CODE_SCOPE 
    UNIQUE (CODE, ROLE_SCOPE_TYPE, SCOPE_ID),

  CONSTRAINT CK_ROLES_SCOPE_VALID
    CHECK (
      (ROLE_SCOPE_TYPE = 'GLOBAL' AND SCOPE_ID IS NULL) OR
      (ROLE_SCOPE_TYPE IN ('TENANT', 'UNIT') AND SCOPE_ID IS NOT NULL)
    ),
    CHECK (LEVEL BETWEEN 0 AND 255)
);

CREATE INDEX IDX_ROLES_SCOPE 
ON ROLES (ROLE_SCOPE_TYPE, SCOPE_ID);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin

DROP TABLE IF EXISTS ROLES;
DROP TYPE IF EXISTS ROLE_ACCESS_SCOPE;
DROP TYPE IF EXISTS ROLE_SCOPE_TYPE;

-- +goose StatementEnd