-- 003_ROLE_PERMISSIONS.sql

-- +goose Up

-- +goose StatementBegin

CREATE TYPE PERMISSION_ACCESS_SCOPE AS ENUM (
    'ALL',
    'OWN'
);

CREATE TABLE ROLE_PERMISSIONS (
    ROLE_ID UUID NOT NULL,
    PERMISSION_ID UUID NOT NULL,

    ACCESS_SCOPE PERMISSION_ACCESS_SCOPE NOT NULL DEFAULT 'ALL',

    GRANTED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    GRANTED_BY UUID,

    CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CREATED_BY UUID,
    UPDATED_BY UUID,

    CONSTRAINT PK_ROLE_PERMISSIONS
        PRIMARY KEY (ROLE_ID, PERMISSION_ID),

    CONSTRAINT FK_ROLE_PERMISSIONS_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES (ID)
        ON DELETE CASCADE,

    CONSTRAINT FK_ROLE_PERMISSIONS_PERMISSION
        FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSIONS (ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_ROLE_PERMISSIONS_PERMISSION
    ON ROLE_PERMISSIONS (PERMISSION_ID);

-- +goose StatementEnd


-- +goose Down

-- +goose StatementBegin

DROP TABLE IF EXISTS ROLE_PERMISSIONS;

DROP TYPE IF EXISTS PERMISSION_ACCESS_SCOPE;

-- +goose StatementEnd