-- +goose Up
-- +goose StatementBegin

CREATE TABLE ROLE_PERMISSIONS (
  ROLE_ID UUID NOT NULL,
  PERMISSION_ID UUID NOT NULL,

  GRANTED_AT TIMESTAMP DEFAULT NOW(),
  GRANTED_BY UUID,

  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  PRIMARY KEY (ROLE_ID, PERMISSION_ID),

  CONSTRAINT FK_RP_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID)
    ON DELETE CASCADE,

  CONSTRAINT FK_RP_PERMISSION
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES PERMISSIONS(ID)
    ON DELETE CASCADE
);

CREATE INDEX IDX_RP_ROLE
ON ROLE_PERMISSIONS(ROLE_ID);

CREATE INDEX IDX_RP_PERMISSION
ON ROLE_PERMISSIONS(PERMISSION_ID);

-- -- ROLE_PERMISSIONS
-- -- Lấy ID của role + permission (ví dụ giả định bạn có gen_random_uuid)
-- -- Giả sử bạn lưu role_id và permission_id vào biến để insert
-- -- Mình viết trực tiếp ví dụ logic

-- -- Super Admin
-- INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
-- SELECT r.ID, p.ID
-- FROM ROLES r, PERMISSIONS p
-- WHERE r.CODE = 'SUPER_ADMIN';

-- -- Restaurant Manager
-- INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
-- SELECT r.ID, p.ID
-- FROM ROLES r, PERMISSIONS p
-- WHERE r.CODE = 'RESTAURANT_MANAGER'
--   AND p.CODE IN ('ORDER_CREATE','ORDER_UPDATE','ORDER_COMPLETE','PRODUCT_MANAGE','PAYMENT_COLLECT');

-- -- Café Operator
-- INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
-- SELECT r.ID, p.ID
-- FROM ROLES r, PERMISSIONS p
-- WHERE r.CODE = 'CAFE_OPERATOR'
--   AND p.CODE IN ('ORDER_CREATE','ORDER_UPDATE','ORDER_COMPLETE','PRODUCT_MANAGE','PAYMENT_COLLECT');

-- -- Street Vendor
-- INSERT INTO ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID)
-- SELECT r.ID, p.ID
-- FROM ROLES r, PERMISSIONS p
-- WHERE r.CODE = 'FB_VENDOR'
--   AND p.CODE IN ('ORDER_CREATE','ORDER_COMPLETE','PRODUCT_MANAGE','PAYMENT_COLLECT');


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS PERMISSIONS;
-- +goose StatementEnd