// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "github.com/vokhanh12/refactor-rongstore-system/server/internal/platform/apperrors"

var (
	LOGIN_EMAIL_EMPTY = apperrors.AppError{
		Key: "LOGIN_EMAIL_EMPTY",
		Code: "AUTH-VAL-001",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Email is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_EMAIL_INVALID = apperrors.AppError{
		Key: "LOGIN_EMAIL_INVALID",
		Code: "AUTH-VAL-002",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid email format",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_PASSWORD_EMPTY = apperrors.AppError{
		Key: "LOGIN_PASSWORD_EMPTY",
		Code: "AUTH-VAL-003",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Password is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	LOGIN_PAYLOAD_INVALID = apperrors.AppError{
		Key: "LOGIN_PAYLOAD_INVALID",
		Code: "AUTH-VAL-004",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid request payload",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	STORE_OWNER_VALIDATE = apperrors.AppError{
		Key: "STORE_OWNER_VALIDATE",
		Code: "AUTH-VAL-006",
		Component: "domain",
		Tags: []string{"validation"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid store owner data",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	VIEW_OPERATION_UNSUPPORTED = apperrors.AppError{
		Key: "VIEW_OPERATION_UNSUPPORTED",
		Code: "AUTH-VAL-011",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Unsupported view operation",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	MUTATE_OPERATION_UNSUPPORTED = apperrors.AppError{
		Key: "MUTATE_OPERATION_UNSUPPORTED",
		Code: "AUTH-VAL-012",
		Component: "api",
		Tags: []string{"validation","client"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Unsupported mutate operation",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	AUTHORIZATION_INVALID = apperrors.AppError{
		Key: "AUTHORIZATION_INVALID",
		Code: "AUTH-VAL-013",
		Component: "authz",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	AUTHORIZATION_RESOURCE_OR_ACTION_REQUIRED = apperrors.AppError{
		Key: "AUTHORIZATION_RESOURCE_OR_ACTION_REQUIRED",
		Code: "AUTHZ-VAL-014",
		Component: "authz",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Resource and action are required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	AUTHORIZATION_ROLE_REQUIRED = apperrors.AppError{
		Key: "AUTHORIZATION_ROLE_REQUIRED",
		Code: "AUTHZ-VAL-015",
		Component: "authz",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Role is required for authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	STORE_OWNER_NOT_FOUND = apperrors.AppError{
		Key: "STORE_OWNER_NOT_FOUND",
		Code: "AUTH-DOM-001",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Store owner not found",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	STORE_OWNER_CONFLICT = apperrors.AppError{
		Key: "STORE_OWNER_CONFLICT",
		Code: "AUTH-DOM-002",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 409,
		GRPCCode: "AlreadyExists",
		Message: "Store owner already exists",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	STORE_OWNER_INVALID = apperrors.AppError{
		Key: "STORE_OWNER_INVALID",
		Code: "AUTH-DOM-003",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Store owner contains invalid references",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	STORE_OWNER_PERSIST_FAILED = apperrors.AppError{
		Key: "STORE_OWNER_PERSIST_FAILED",
		Code: "AUTH-DOM-004",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to persist store owner",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_NOT_FOUND = apperrors.AppError{
		Key: "ROLE_NOT_FOUND",
		Code: "AUTHZ-DOM-001",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Role not found",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_CONFLICT = apperrors.AppError{
		Key: "ROLE_CONFLICT",
		Code: "AUTHZ-DOM-002",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 409,
		GRPCCode: "AlreadyExists",
		Message: "Role already exists",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_INVALID = apperrors.AppError{
		Key: "ROLE_INVALID",
		Code: "AUTHZ-DOM-003",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Role contains invalid references",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_PERSIST_FAILED = apperrors.AppError{
		Key: "ROLE_PERSIST_FAILED",
		Code: "AUTHZ-DOM-004",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to persist role",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	PERMISSION_NOT_FOUND = apperrors.AppError{
		Key: "PERMISSION_NOT_FOUND",
		Code: "AUTHZ-DOM-005",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Permission not found",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	PERMISSION_CONFLICT = apperrors.AppError{
		Key: "PERMISSION_CONFLICT",
		Code: "AUTHZ-DOM-006",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 409,
		GRPCCode: "AlreadyExists",
		Message: "Permission already exists",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	PERMISSION_INVALID = apperrors.AppError{
		Key: "PERMISSION_INVALID",
		Code: "AUTHZ-DOM-007",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Permission contains invalid references",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	PERMISSION_PERSIST_FAILED = apperrors.AppError{
		Key: "PERMISSION_PERSIST_FAILED",
		Code: "AUTHZ-DOM-008",
		Component: "domain",
		Tags: []string{"domain"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to persist permission",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	TOKEN_EXPIRED = apperrors.AppError{
		Key: "TOKEN_EXPIRED",
		Code: "AUTH-SEC-001",
		Component: "jwt",
		Tags: []string{"security","auth"},
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Token expired",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	UNAUTHORIZED = apperrors.AppError{
		Key: "UNAUTHORIZED",
		Code: "AUTH-SEC-002",
		Component: "auth",
		Tags: []string{"security","auth"},
		Status: 401,
		GRPCCode: "Unauthenticated",
		Message: "Authentication required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_FORBIDDEN = apperrors.AppError{
		Key: "ROLE_FORBIDDEN",
		Code: "AUTH-SEC-003",
		Component: "authz",
		Tags: []string{"security","authz"},
		Status: 403,
		GRPCCode: "PermissionDenied",
		Message: "Permission denied",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	HANDSHAKE_INVALID_CLIENT_KEY = apperrors.AppError{
		Key: "HANDSHAKE_INVALID_CLIENT_KEY",
		Code: "AUTH-PROTO-001",
		Component: "handshake",
		Tags: []string{"protocol","security"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid client public key",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	HANDSHAKE_KEY_AGREEMENT_FAIL = apperrors.AppError{
		Key: "HANDSHAKE_KEY_AGREEMENT_FAIL",
		Code: "AUTH-PROTO-002",
		Component: "handshake",
		Tags: []string{"protocol","crypto"},
		Status: 422,
		GRPCCode: "FailedPrecondition",
		Message: "Key agreement failed",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_TIMEOUT = apperrors.AppError{
		Key: "DB_TIMEOUT",
		Code: "AUTH-INFRA-001",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Database service temporarily unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_QUERY_TIMEOUT = apperrors.AppError{
		Key: "DB_QUERY_TIMEOUT",
		Code: "AUTH-INFRA-010",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Database query timeout",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_QUERY_FAILED = apperrors.AppError{
		Key: "DB_QUERY_FAILED",
		Code: "AUTH-INFRA-011",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Database query failed",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	DB_CONFLICT_RETRYABLE = apperrors.AppError{
		Key: "DB_CONFLICT_RETRYABLE",
		Code: "AUTH-INFRA-002",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Concurrent update conflict",
		Severity: "S2",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	REDIS_UNAVAILABLE = apperrors.AppError{
		Key: "REDIS_UNAVAILABLE",
		Code: "AUTH-INFRA-003",
		Component: "redis",
		Tags: []string{"infra","cache"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Redis unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	KEYCLOAK_UNAVAILABLE = apperrors.AppError{
		Key: "KEYCLOAK_UNAVAILABLE",
		Code: "AUTH-INFRA-004",
		Component: "keycloak",
		Tags: []string{"infra","external","auth"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Keycloak unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	POSTGRES_UNAVAILABLE = apperrors.AppError{
		Key: "POSTGRES_UNAVAILABLE",
		Code: "AUTH-INFRA-005",
		Component: "postgres",
		Tags: []string{"infra","database"},
		Status: 503,
		GRPCCode: "Unavailable",
		Message: "Postgres unavailable",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	HANDSHAKE_RNG_FAIL = apperrors.AppError{
		Key: "HANDSHAKE_RNG_FAIL",
		Code: "AUTH-INFRA-006",
		Component: "crypto",
		Tags: []string{"infra","crypto"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Random generation failed",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	HANDSHAKE_KEY_DERIVE_FAIL = apperrors.AppError{
		Key: "HANDSHAKE_KEY_DERIVE_FAIL",
		Code: "AUTH-INFRA-007",
		Component: "crypto",
		Tags: []string{"infra","crypto"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Key derivation failed",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	HANDSHAKE_STORAGE_FAIL = apperrors.AppError{
		Key: "HANDSHAKE_STORAGE_FAIL",
		Code: "AUTH-INFRA-008",
		Component: "redis",
		Tags: []string{"infra","cache"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to store session",
		Severity: "S1",
		Retryable: true,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	JSON_SERIALIZATION_FAILED = apperrors.AppError{
		Key: "JSON_SERIALIZATION_FAILED",
		Code: "AUTH-INFRA-009",
		Component: "api",
		Tags: []string{"infra"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to serialize request payload",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

)

var (
	REASON_OUT_OF_RANGE = apperrors.AppErrorDetail{
		Code: "OUT_OF_RANGE",
		Message: "Out of range",
	}

	REASON_REQUIRED = apperrors.AppErrorDetail{
		Code: "REQUIRED",
		Message: "Required",
	}

	REASON_INVALID_FORMAT = apperrors.AppErrorDetail{
		Code: "INVALID_FORMAT",
		Message: "Invalid format",
	}

	REASON_DUPLICATE = apperrors.AppErrorDetail{
		Code: "DUPLICATE",
		Message: "Duplicate",
	}

	REASON_NOT_FOUND = apperrors.AppErrorDetail{
		Code: "NOT_FOUND",
		Message: "Not found",
	}

)

// ErrorByCode maps error codes to AppError
var ErrorByCode = map[string]apperrors.AppError{
	"AUTH-VAL-001": LOGIN_EMAIL_EMPTY,
	"AUTH-VAL-002": LOGIN_EMAIL_INVALID,
	"AUTH-VAL-003": LOGIN_PASSWORD_EMPTY,
	"AUTH-VAL-004": LOGIN_PAYLOAD_INVALID,
	"AUTH-VAL-006": STORE_OWNER_VALIDATE,
	"AUTH-VAL-011": VIEW_OPERATION_UNSUPPORTED,
	"AUTH-VAL-012": MUTATE_OPERATION_UNSUPPORTED,
	"AUTH-VAL-013": AUTHORIZATION_INVALID,
	"AUTHZ-VAL-014": AUTHORIZATION_RESOURCE_OR_ACTION_REQUIRED,
	"AUTHZ-VAL-015": AUTHORIZATION_ROLE_REQUIRED,
	"AUTH-DOM-001": STORE_OWNER_NOT_FOUND,
	"AUTH-DOM-002": STORE_OWNER_CONFLICT,
	"AUTH-DOM-003": STORE_OWNER_INVALID,
	"AUTH-DOM-004": STORE_OWNER_PERSIST_FAILED,
	"AUTHZ-DOM-001": ROLE_NOT_FOUND,
	"AUTHZ-DOM-002": ROLE_CONFLICT,
	"AUTHZ-DOM-003": ROLE_INVALID,
	"AUTHZ-DOM-004": ROLE_PERSIST_FAILED,
	"AUTHZ-DOM-005": PERMISSION_NOT_FOUND,
	"AUTHZ-DOM-006": PERMISSION_CONFLICT,
	"AUTHZ-DOM-007": PERMISSION_INVALID,
	"AUTHZ-DOM-008": PERMISSION_PERSIST_FAILED,
	"AUTH-SEC-001": TOKEN_EXPIRED,
	"AUTH-SEC-002": UNAUTHORIZED,
	"AUTH-SEC-003": ROLE_FORBIDDEN,
	"AUTH-PROTO-001": HANDSHAKE_INVALID_CLIENT_KEY,
	"AUTH-PROTO-002": HANDSHAKE_KEY_AGREEMENT_FAIL,
	"AUTH-INFRA-001": DB_TIMEOUT,
	"AUTH-INFRA-010": DB_QUERY_TIMEOUT,
	"AUTH-INFRA-011": DB_QUERY_FAILED,
	"AUTH-INFRA-002": DB_CONFLICT_RETRYABLE,
	"AUTH-INFRA-003": REDIS_UNAVAILABLE,
	"AUTH-INFRA-004": KEYCLOAK_UNAVAILABLE,
	"AUTH-INFRA-005": POSTGRES_UNAVAILABLE,
	"AUTH-INFRA-006": HANDSHAKE_RNG_FAIL,
	"AUTH-INFRA-007": HANDSHAKE_KEY_DERIVE_FAIL,
	"AUTH-INFRA-008": HANDSHAKE_STORAGE_FAIL,
	"AUTH-INFRA-009": JSON_SERIALIZATION_FAILED,
}

// ErrorDetailByCode maps detail codes to AppErrorDetail
var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{
	"OUT_OF_RANGE": REASON_OUT_OF_RANGE,
	"REQUIRED": REASON_REQUIRED,
	"INVALID_FORMAT": REASON_INVALID_FORMAT,
	"DUPLICATE": REASON_DUPLICATE,
	"NOT_FOUND": REASON_NOT_FOUND,
}

