// Code generated by generate_errors.sh. DO NOT EDIT.

package apperrors

import "google.golang.org/grpc/codes"

var (
	UNKNOWN_DOMAIN = AppError{
		Key:       "UNKNOWN_DOMAIN",
		Code:      "CORE-DOM-999",
		Domain:    "core",
		Layer:     "DOM",
		Status:    400,
		GRPCCode:  codes.InvalidArgument,
		Message:   "Unknown domain error",
		Severity:  "S1",
		Retryable: false,
	}

	INTERNAL_FALLBACK = AppError{
		Key:       "INTERNAL_FALLBACK",
		Code:      "CORE-SYS-999",
		Domain:    "core",
		Layer:     "SYS",
		Status:    500,
		GRPCCode:  codes.Internal,
		Message:   "Internal server error",
		Severity:  "S1",
		Retryable: false,
	}

)

var ErrorByCode = map[string]AppError{
	"CORE-DOM-999": UNKNOWN_DOMAIN,
	"CORE-SYS-999": INTERNAL_FALLBACK,
}
