#!/usr/bin/env bash
set -euo pipefail

YAML_FILE="../app_errors.yaml"

# Validate YAML tồn tại
if [ ! -f "$YAML_FILE" ]; then
	echo "❌ YAML file not found: $YAML_FILE"
	exit 1
fi

services=$(yq e '.services | keys | .[]' "$YAML_FILE")

for svc in $services; do

	echo "➡️ Generating errors for service: $svc"

	OUTPUT_FILE="../server/internal/$svc/errors/errors_gen.go"
	mkdir -p "$(dirname "$OUTPUT_FILE")"
	rm -f "$OUTPUT_FILE"

	# ============================================================
	# INIT
	# ============================================================

	error_keys=()
	error_detail_keys=()

	seen_keys=""
	seen_codes=""
	seen_detail_codes=""

	# ============================================================
	# FILE HEADER
	# ============================================================

	cat <<EOF > "$OUTPUT_FILE"
// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "github.com/vokhanh12/refactor-rongstore-system/server/internal/platform/apperrors"

var (
EOF

	# ============================================================
	# LOAD ERRORS (support both flat + category)
	# ============================================================

	errors_json=$(yq e ".services.$svc.errors" -o=json "$YAML_FILE")

	# Flatten:
	# - nếu là array → dùng luôn
	# - nếu là object (VAL, DOM, ...) → flatten hết
	flattened=$(echo "$errors_json" | jq -c '
		if type == "array" then .[]
		else to_entries[] | .value[] end
	')

	# ============================================================
	# GENERATE ERRORS
	# ============================================================

	while IFS="|" read -r key code component tags status grpc_code message severity retryable cause client_action server_action; do

		# Skip empty
		[ -z "$key" ] && continue

		# ---------- Validate key ----------
		if echo "$seen_keys" | grep -wq "$key"; then
			echo "❌ Duplicate error key detected: $key"
			exit 1
		fi
		seen_keys="$seen_keys $key"

		# ---------- Validate code ----------
		if echo "$seen_codes" | grep -wq "$code"; then
			echo "❌ Duplicate error code detected: $code (key: $key)"
			exit 1
		fi
		seen_codes="$seen_codes $code"

		# ---------- Validate format ----------
		[[ "$key" =~ ^[A-Z0-9_]+$ ]] || { echo "❌ Invalid key: $key"; exit 1; }
		[[ "$code" =~ ^[A-Z]+-[A-Z]+-[0-9]+$ ]] || { echo "❌ Invalid code: $code"; exit 1; }

		error_keys+=("$key:$code")

		cat <<EOF >> "$OUTPUT_FILE"
	$key = apperrors.AppError{
		Key: "$key",
		Code: "$code",
		Component: "$component",
		Tags: []string{$tags},
		Status: $status,
		GRPCCode: "$grpc_code",
		Message: "$message",
		Severity: "$severity",
		Retryable: $retryable,
		Cause: "$cause",
		ClientAction: "$client_action",
		ServerAction: "$server_action",
	}

EOF

	done < <(
		echo "$flattened" | jq -r '
		[
			.key,
			.code,
			(.component // ""),
			((.tags // []) | map("\""+.+"\"") | join(",")),
			(.http_status|tostring),
			.grpc_code,
			.message,
			(.severity // ""),
			(.retryable // false|tostring),
			(.cause // ""),
			(.client_action // ""),
			(.server_action // "")
		] | join("|")
		'
	)

	echo ")" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

	# ============================================================
	# ERROR DETAILS
	# ============================================================

	if yq e ".services.$svc.errors_detail" "$YAML_FILE" > /dev/null 2>&1; then

		details=$(yq e ".services.$svc.errors_detail[]" -o=json "$YAML_FILE" 2>/dev/null || true)

		if [ -n "$details" ]; then

			echo "var (" >> "$OUTPUT_FILE"

			while IFS="|" read -r code message; do

				[ -z "$code" ] && continue

				if echo "$seen_detail_codes" | grep -wq "$code"; then
					echo "❌ Duplicate error detail code: $code"
					exit 1
				fi
				seen_detail_codes="$seen_detail_codes $code"

				const_name="REASON_${code}"
				error_detail_keys+=("$const_name:$code")

				cat <<EOF >> "$OUTPUT_FILE"
	$const_name = apperrors.AppErrorDetail{
		Code: "$code",
		Message: "$message",
	}

EOF

			done < <(
				echo "$details" | jq -r '[.code,.message] | join("|")'
			)

			echo ")" >> "$OUTPUT_FILE"
			echo "" >> "$OUTPUT_FILE"
		fi
	fi

	# ============================================================
	# MAP: ErrorByCode
	# ============================================================

	echo "// ErrorByCode maps error codes to AppError" >> "$OUTPUT_FILE"
	echo "var ErrorByCode = map[string]apperrors.AppError{" >> "$OUTPUT_FILE"

	for pair in "${error_keys[@]:-}"; do
		key="${pair%%:*}"
		code="${pair##*:}"
		echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
	done

	echo "}" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

	# ============================================================
	# MAP: ErrorDetailByCode
	# ============================================================

	if [ ${#error_detail_keys[@]} -gt 0 ]; then
		echo "// ErrorDetailByCode maps detail codes to AppErrorDetail" >> "$OUTPUT_FILE"
		echo "var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{" >> "$OUTPUT_FILE"

		for pair in "${error_detail_keys[@]}"; do
			key="${pair%%:*}"
			code="${pair##*:}"
			echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
		done

		echo "}" >> "$OUTPUT_FILE"
		echo "" >> "$OUTPUT_FILE"
	fi

done

# ============================================================
# DEFAULT ERRORS
# ============================================================

OUTPUT_DEFAULT_FILE="../pkg/apperrors/errors_gen.go"
mkdir -p "$(dirname "$OUTPUT_DEFAULT_FILE")"
rm -f "$OUTPUT_DEFAULT_FILE"

cat <<EOF > "$OUTPUT_DEFAULT_FILE"
// Code generated by generate_errors.sh. DO NOT EDIT.
package apperrors

var (
EOF

default_keys=()
seen_default_codes=""

defaults=$(yq e ".defaults" -o=json "$YAML_FILE" |
jq -r '
to_entries[]
| [
.key,
.value.code,
(.value.http_status|tostring),
.value.grpc_code,
.value.message,
"S1",
"false"
]
| join("|")
'
)

while IFS="|" read -r key code status grpc_code message severity retryable; do

	[ -z "$key" ] && continue

	if echo "$seen_default_codes" | grep -wq "$code"; then
		echo "❌ Duplicate default error code: $code"
		exit 1
	fi
	seen_default_codes="$seen_default_codes $code"

	default_keys+=("$key:$code")

	cat <<EOF >> "$OUTPUT_DEFAULT_FILE"
	$key = AppError{
		Key: "$key",
		Code: "$code",
		Status: $status,
		GRPCCode: "$grpc_code",
		Message: "$message",
		Severity: "$severity",
		Retryable: $retryable,
	}

EOF

done < <(echo "$defaults")

echo ")" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"

echo "var ErrorByCode = map[string]AppError{" >> "$OUTPUT_DEFAULT_FILE"

for pair in "${default_keys[@]:-}"; do
	key="${pair%%:*}"
	code="${pair##*:}"
	echo -e "\t\"$code\": $key," >> "$OUTPUT_DEFAULT_FILE"
done

echo "}" >> "$OUTPUT_DEFAULT_FILE"

echo "✅ Done generating errors"