#!/usr/bin/env bash
set -euo pipefail

YAML_FILE="../app_errors.yaml"

services=$(yq e '.services | keys | .[]' "$YAML_FILE")

for svc in $services; do

OUTPUT_FILE="../server/internal/$svc/errors/errors_gen.go"
mkdir -p "$(dirname "$OUTPUT_FILE")"
rm -f "$OUTPUT_FILE"

echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_FILE"
echo "package domain" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "import \"github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors\"" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "var (" >> "$OUTPUT_FILE"

error_keys=()
error_detail_keys=()

# ------------------------------------------------------------
# Flatten all category errors
# ------------------------------------------------------------

while IFS="|" read -r key code component tags status grpc_code message severity retryable cause client_action server_action; do

error_keys+=("$key:$code")

{
echo -e "\t${key} = apperrors.AppError{"
echo -e "\t\tKey: \"$key\","
echo -e "\t\tCode: \"$code\","
echo -e "\t\tComponent: \"$component\","
echo -e "\t\tTags: []string{$tags},"
echo -e "\t\tStatus: $status,"
echo -e "\t\tGRPCCode: \"$grpc_code\","
echo -e "\t\tMessage: \"$message\","
echo -e "\t\tSeverity: \"$severity\","
echo -e "\t\tRetryable: $retryable,"
echo -e "\t\tCause: \"$cause\","
echo -e "\t\tClientAction: \"$client_action\","
echo -e "\t\tServerAction: \"$server_action\","
echo -e "\t}"
echo ""
} >> "$OUTPUT_FILE"

done < <(

yq e ".services.$svc.errors.*[]" -o=json "$YAML_FILE" |
jq -r '
[
.key,
.code,
(.component // ""),
((.tags // []) | map("\""+.+"\"") | join(",")),
(.http_status|tostring),
.grpc_code,
.message,
(.severity // ""),
(.retryable // false|tostring),
(.cause // ""),
(.client_action // ""),
(.server_action // "")
] | join("|")
'

)

echo ")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# ------------------------------------------------------------
# Generate error details
# ------------------------------------------------------------

if yq e ".services.$svc.errors_detail" "$YAML_FILE" > /dev/null 2>&1; then

echo "var (" >> "$OUTPUT_FILE"

while IFS="|" read -r code message; do

const_name="REASON_${code}"
error_detail_keys+=("$const_name:$code")

{
echo -e "\t${const_name} = apperrors.AppErrorDetail{"
echo -e "\t\tCode: \"$code\","
echo -e "\t\tMessage: \"$message\","
echo -e "\t}"
echo ""
} >> "$OUTPUT_FILE"

done < <(

yq e ".services.$svc.errors_detail[]" -o=json "$YAML_FILE" |
jq -r '[.code,.message] | join("|")'

)

echo ")" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

fi

# ------------------------------------------------------------
# Map ErrorByCode
# ------------------------------------------------------------

echo "// ErrorByCode maps error codes to AppError" >> "$OUTPUT_FILE"
echo "var ErrorByCode = map[string]apperrors.AppError{" >> "$OUTPUT_FILE"

for pair in "${error_keys[@]}"; do
key="${pair%%:*}"
code="${pair##*:}"
echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
done

echo "}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# ------------------------------------------------------------
# Map ErrorDetailByCode
# ------------------------------------------------------------

echo "// ErrorDetailByCode maps detail codes to AppErrorDetail" >> "$OUTPUT_FILE"
echo "var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{" >> "$OUTPUT_FILE"

for pair in "${error_detail_keys[@]}"; do
key="${pair%%:*}"
code="${pair##*:}"
echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"
done

echo "}" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

done

# ------------------------------------------------------------
# Generate default errors
# ------------------------------------------------------------

OUTPUT_DEFAULT_FILE="../pkg/apperrors/errors_gen.go"
mkdir -p "$(dirname "$OUTPUT_DEFAULT_FILE")"
rm -f "$OUTPUT_DEFAULT_FILE"

echo "// Code generated by generate_errors.sh. DO NOT EDIT." > "$OUTPUT_DEFAULT_FILE"
echo "package errors" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"
echo "var (" >> "$OUTPUT_DEFAULT_FILE"

default_keys=()

defaults_data=$(yq e ".defaults" -o=json "$YAML_FILE" |
jq -r '
to_entries[]
| [
.key,
.value.code,
(.value.http_status|tostring),
.value.grpc_code,
.value.message,
"S1",
"false"
]
| join("|")
'
)

while IFS="|" read -r key code status grpc_code message severity retryable; do

default_keys+=("$key:$code")

{
echo -e "\t${key} = AppError{"
echo -e "\t\tKey: \"$key\","
echo -e "\t\tCode: \"$code\","
echo -e "\t\tStatus: $status,"
echo -e "\t\tGRPCCode: \"$grpc_code\","
echo -e "\t\tMessage: \"$message\","
echo -e "\t\tSeverity: \"$severity\","
echo -e "\t\tRetryable: $retryable,"
echo -e "\t}"
echo ""
} >> "$OUTPUT_DEFAULT_FILE"

done < <(echo "$defaults_data")

echo ")" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"

echo "// ErrorByCode maps default error codes to AppError definitions" >> "$OUTPUT_DEFAULT_FILE"
echo "var ErrorByCode = map[string]AppError{" >> "$OUTPUT_DEFAULT_FILE"

for pair in "${default_keys[@]}"; do
key="${pair%%:*}"
code="${pair##*:}"
echo -e "\t\"$code\": $key," >> "$OUTPUT_DEFAULT_FILE"
done

echo "}" >> "$OUTPUT_DEFAULT_FILE"