#!/usr/bin/env bash
set -euo pipefail

YAML_FILE="../app_errors.yaml"

# ============================================================
# VALIDATE YAML FILE
# ============================================================

if [ ! -f "$YAML_FILE" ]; then
	echo "❌ YAML file not found: $YAML_FILE"
	exit 1
fi

# ============================================================
# CLEAN OLD GENERATED FILES
# ============================================================

echo "🧹 Cleaning old generated files..."

find ../server/internal -type f -name "errors_gen.go" -delete
find ../server/pkg/apperrors -type f -name "errors_gen.go" -delete

echo "✅ Old generated files removed"
echo ""


# ============================================================
# GLOBAL TRACKING
# ============================================================

GLOBAL_SEEN_KEYS=""
GLOBAL_SEEN_CODES=""
GLOBAL_SEEN_DEFAULT_CODES=""

VALID_LAYERS="DOM APP TRANS PARSE INFRA SEC SYS"

# ============================================================
# LOAD GLOBAL ERROR DETAILS ONCE
# ============================================================

DETAIL_KEYS=()
DETAIL_CODES=""

details_json=$(yq e '.error_details' -o=json "$YAML_FILE" 2>/dev/null || echo "{}")

while IFS="|" read -r code message; do

	[ -z "$code" ] && continue

	# duplicate detail code
	if echo "$DETAIL_CODES" | grep -wq "$code"; then
		echo "❌ Duplicate detail code: $code"
		exit 1
	fi

	DETAIL_CODES="$DETAIL_CODES $code"

	DETAIL_KEYS+=("REASON_${code}:$code:$message")

done < <(
	echo "$details_json" | jq -r '
		to_entries[]
		| .value[]
		| [
			.code,
			.message
		]
		| join("|")
	'
)

# ============================================================
# GET ALL SERVICES
# ============================================================

services=$(yq e -o=json '.services' "$YAML_FILE" | jq -r '
	paths
	| select(.[-1] == "errors")
	| .[0:-1]
	| map(tostring)
	| join(".")
')

# ============================================================
# LOOP SERVICES
# ============================================================

for svc in $services; do

	echo "➡️ Generating errors for service: $svc"

	# iam.auth -> iam/auth
	svc_path=$(echo "$svc" | tr '.' '/')

	OUTPUT_FILE="../server/internal/$svc_path/errors/errors_gen.go"

	mkdir -p "$(dirname "$OUTPUT_FILE")"
	rm -f "$OUTPUT_FILE"

	error_keys=()

	# ========================================================
	# FILE HEADER
	# ========================================================

	cat <<EOF > "$OUTPUT_FILE"
// Code generated by generate_errors.sh. DO NOT EDIT.

package errors

import "github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors"

var (
EOF

	# ========================================================
	# LOAD ERRORS
	# ========================================================

	errors_json=$(yq e ".services.$svc.errors" -o=json "$YAML_FILE" 2>/dev/null || echo "null")

	if [ "$errors_json" = "null" ]; then
		echo "⚠️ Skip (no errors): $svc"
		continue
	fi

	# ========================================================
	# FLATTEN LAYERS
	# ========================================================

	flattened=$(echo "$errors_json" | jq -c '
		to_entries[]
		| .value[]
	')

	# ========================================================
	# GENERATE ERRORS
	# ========================================================

	while IFS="|" read -r key code component tags status grpc_code message severity retryable cause client_action server_action; do

		[ -z "$key" ] && continue

		# ====================================================
		# VALIDATE KEY
		# ====================================================

		[[ "$key" =~ ^[A-Z0-9_]+$ ]] || {
			echo "❌ Invalid key: $key"
			exit 1
		}

		# ====================================================
		# VALIDATE CODE
		# ====================================================

		[[ "$code" =~ ^[A-Z0-9]+-[A-Z0-9]+-[0-9]{3}$ ]] || {
			echo "❌ Invalid code format: $code"
			exit 1
		}

		# ====================================================
		# VALIDATE LAYER
		# ====================================================

		layer=$(echo "$code" | cut -d'-' -f2)

		if ! echo "$VALID_LAYERS" | grep -wq "$layer"; then
			echo "❌ Invalid layer: $layer ($code)"
			exit 1
		fi

		# ====================================================
		# DUPLICATE KEY
		# ====================================================

		if echo "$GLOBAL_SEEN_KEYS" | grep -wq "$key"; then
			echo "❌ Duplicate key: $key"
			exit 1
		fi

		GLOBAL_SEEN_KEYS="$GLOBAL_SEEN_KEYS $key"

		# ====================================================
		# DUPLICATE CODE
		# ====================================================

		if echo "$GLOBAL_SEEN_CODES" | grep -wq "$code"; then
			echo "❌ Duplicate code: $code"
			exit 1
		fi

		GLOBAL_SEEN_CODES="$GLOBAL_SEEN_CODES $code"

		error_keys+=("$key:$code")

		# ====================================================
		# GENERATE ERROR
		# ====================================================

		cat <<EOF >> "$OUTPUT_FILE"
	$key = apperrors.AppError{
		Key: "$key",
		Code: "$code",
		Layer: "$layer",
		Component: "$component",
		Tags: []string{$tags},
		Status: $status,
		GRPCCode: "$grpc_code",
		Message: "$message",
		Severity: "$severity",
		Retryable: $retryable,
		Cause: "$cause",
		ClientAction: "$client_action",
		ServerAction: "$server_action",
	}

EOF

	done < <(
		echo "$flattened" | jq -r '
		[
			.key,
			.code,
			(.component // ""),
			((.tags // []) | map("\""+.+"\"") | join(",")),
			(.http_status | tostring),
			.grpc_code,
			.message,
			(.severity // "S3"),
			(.retryable // false | tostring),
			(.cause // ""),
			(.client_action // ""),
			(.server_action // "")
		]
		| join("|")
		'
	)

	echo ")" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

	# ========================================================
	# ERROR DETAILS
	# ========================================================

	echo "var (" >> "$OUTPUT_FILE"

	for pair in "${DETAIL_KEYS[@]}"; do

		const_name=$(echo "$pair" | cut -d':' -f1)
		code=$(echo "$pair" | cut -d':' -f2)
		message=$(echo "$pair" | cut -d':' -f3-)

		cat <<EOF >> "$OUTPUT_FILE"
	$const_name = apperrors.AppErrorDetail{
		Code: "$code",
		Message: "$message",
	}

EOF

	done

	echo ")" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

	# ========================================================
	# ERROR BY CODE
	# ========================================================

	echo "var ErrorByCode = map[string]apperrors.AppError{" >> "$OUTPUT_FILE"

	for pair in "${error_keys[@]}"; do

		key="${pair%%:*}"
		code="${pair##*:}"

		echo -e "\t\"$code\": $key," >> "$OUTPUT_FILE"

	done

	echo "}" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

	# ========================================================
	# ERROR DETAIL BY CODE
	# ========================================================

	echo "var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{" >> "$OUTPUT_FILE"

	for pair in "${DETAIL_KEYS[@]}"; do

		const_name=$(echo "$pair" | cut -d':' -f1)
		code=$(echo "$pair" | cut -d':' -f2)

		echo -e "\t\"$code\": $const_name," >> "$OUTPUT_FILE"

	done

	echo "}" >> "$OUTPUT_FILE"
	echo "" >> "$OUTPUT_FILE"

done

# ============================================================
# DEFAULT ERRORS
# ============================================================

OUTPUT_DEFAULT_FILE="../server/pkg/apperrors/errors_gen.go"

mkdir -p "$(dirname "$OUTPUT_DEFAULT_FILE")"
rm -f "$OUTPUT_DEFAULT_FILE"

cat <<EOF > "$OUTPUT_DEFAULT_FILE"
// Code generated by generate_errors.sh. DO NOT EDIT.

package apperrors

var (
EOF

default_keys=()

defaults=$(yq e ".defaults" -o=json "$YAML_FILE" | jq -r '
	to_entries[]
	| [
		.key,
		.value.code,
		(.value.http_status | tostring),
		.value.grpc_code,
		.value.message,
		(.value.severity // "S1"),
		(.value.retryable // false | tostring)
	]
	| join("|")
')

while IFS="|" read -r key code status grpc_code message severity retryable; do

	[ -z "$key" ] && continue

	# ========================================================
	# DUPLICATE DEFAULT CODE
	# ========================================================

	if echo "$GLOBAL_SEEN_DEFAULT_CODES" | grep -wq "$code"; then
		echo "❌ Duplicate default code: $code"
		exit 1
	fi

	GLOBAL_SEEN_DEFAULT_CODES="$GLOBAL_SEEN_DEFAULT_CODES $code"

	layer=$(echo "$code" | cut -d'-' -f2)

	default_keys+=("$key:$code")

	cat <<EOF >> "$OUTPUT_DEFAULT_FILE"
	$key = AppError{
		Key: "$key",
		Code: "$code",
		Layer: "$layer",
		Status: $status,
		GRPCCode: "$grpc_code",
		Message: "$message",
		Severity: "$severity",
		Retryable: $retryable,
	}

EOF

done < <(echo "$defaults")

echo ")" >> "$OUTPUT_DEFAULT_FILE"
echo "" >> "$OUTPUT_DEFAULT_FILE"

# ============================================================
# DEFAULT ERROR MAP
# ============================================================

echo "var ErrorByCode = map[string]AppError{" >> "$OUTPUT_DEFAULT_FILE"

for pair in "${default_keys[@]}"; do

	key="${pair%%:*}"
	code="${pair##*:}"

	echo -e "\t\"$code\": $key," >> "$OUTPUT_DEFAULT_FILE"

done

echo "}" >> "$OUTPUT_DEFAULT_FILE"

echo ""
echo "✅ Done generating errors"