-- +goose Up
-- +goose StatementBegin

CREATE TABLE ROLE_PERMISSIONS (
  ROLE_ID UUID NOT NULL,
  PERMISSION_ID UUID NOT NULL,

  GRANTED_AT TIMESTAMP DEFAULT NOW(),
  GRANTED_BY UUID,

  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  PRIMARY KEY (ROLE_ID, PERMISSION_ID),

  CONSTRAINT FK_RP_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID)
    ON DELETE CASCADE,

  CONSTRAINT FK_RP_PERMISSION
    FOREIGN KEY (PERMISSION_ID)
    REFERENCES PERMISSIONS(ID)
    ON DELETE CASCADE
);

CREATE INDEX IDX_RP_ROLE
ON ROLE_PERMISSIONS(ROLE_ID);

CREATE INDEX IDX_RP_PERMISSION
ON ROLE_PERMISSIONS(PERMISSION_ID);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS PERMISSIONS;
-- +goose StatementEnd