-- +goose Up
-- +goose StatementBegin

CREATE TABLE ROLE_ASSIGNEMENTS (
  USER_ID UUID NOT NULL,
  ROLE_ID UUID NOT NULL,
  SCOPE_ID UUID NOT NULL,

  SCOPE_TYPE VARCHAR(30) NOT NULL, -- GLOBAL | UNIT | TENANT | OWN

  ASSIGNED_AT TIMESTAMP DEFAULT NOW(),
  ASSIGNED_BY UUID,

  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  PRIMARY KEY (USER_ID, ROLE_ID, SCOPE_ID),

  CONSTRAINT FK_RA_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID)
    ON DELETE CASCADE,

  CONSTRAINT FK_RA_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID)
    ON DELETE CASCADE
);

-- Index để query nhanh
CREATE INDEX IDX_RA_ROLE
ON ROLE_ASSIGNEMENTS(ROLE_ID);

CREATE INDEX IDX_RA_USER
ON ROLE_ASSIGNEMENTS(USER_ID);

CREATE INDEX IDX_RA_SCOPE
ON ROLE_ASSIGNEMENTS(SCOPE_ID);

-- -- ROLE_ASSIGNEMENTS
-- -- User1 là super admin toàn hệ thống
-- INSERT INTO ROLE_ASSIGNEMENTS (USER_ID, ROLE_ID, SCOPE_ID, SCOPE_TYPE, ASSIGNED_BY)
-- SELECT u.ID, r.ID, NULL, 'GLOBAL', u.ID
-- FROM USERS u, ROLES r
-- WHERE u.ID = 'user1-uuid' -- thay bằng UUID thực tế
--   AND r.CODE = 'SUPER_ADMIN';

-- -- User2 là manager một unit nhà hàng
-- INSERT INTO ROLE_ASSIGNEMENTS (USER_ID, ROLE_ID, SCOPE_ID, SCOPE_TYPE, ASSIGNED_BY)
-- SELECT u.ID, r.ID, 'unit-uuid-123', 'UNIT', 'user1-uuid'
-- FROM USERS u, ROLES r
-- WHERE u.ID = 'user2-uuid'
--   AND r.CODE = 'RESTAURANT_MANAGER';

-- -- User3 là street vendor
-- INSERT INTO ROLE_ASSIGNEMENTS (USER_ID, ROLE_ID, SCOPE_ID, SCOPE_TYPE, ASSIGNED_BY)
-- SELECT u.ID, r.ID, 'vendor-unit-uuid', 'OWN', 'user1-uuid'
-- FROM USERS u, ROLES r
-- WHERE u.ID = 'user3-uuid'
--   AND r.CODE = 'FB_VENDOR';

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ROLE_ASSIGNEMENTS;
-- +goose StatementEnd