-- +goose Up
-- +goose StatementBegin

CREATE TABLE ROLE_ASSIGNEMENTS (
  USER_ID UUID NOT NULL,
  ROLE_ID UUID NOT NULL,
  SCOPE_ID UUID NOT NULL,

  SCOPE_TYPE VARCHAR(30) NOT NULL, -- GLOBAL | UNIT | TENANT | OWN

  ASSIGNED_AT TIMESTAMP DEFAULT NOW(),
  ASSIGNED_BY UUID,

  CREATED_AT TIMESTAMP DEFAULT NOW(),
  UPDATED_AT TIMESTAMP DEFAULT NOW(),
  CREATED_BY UUID,
  UPDATED_BY UUID,

  PRIMARY KEY (USER_ID, ROLE_ID, SCOPE_ID),

  CONSTRAINT FK_RA_ROLE
    FOREIGN KEY (ROLE_ID)
    REFERENCES ROLES(ID)
    ON DELETE CASCADE,

  CONSTRAINT FK_RA_USER
    FOREIGN KEY (USER_ID)
    REFERENCES USERS(ID)
    ON DELETE CASCADE
);

-- Index để query nhanh
CREATE INDEX IDX_RA_ROLE
ON ROLE_ASSIGNEMENTS(ROLE_ID);

CREATE INDEX IDX_RA_USER
ON ROLE_ASSIGNEMENTS(USER_ID);

CREATE INDEX IDX_RA_SCOPE
ON ROLE_ASSIGNEMENTS(SCOPE_ID);

-- +goose StatementEnd


-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ROLE_ASSIGNEMENTS;
-- +goose StatementEnd