// Code generated by generate_errors.sh. DO NOT EDIT.
package domain

import "github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors"

var (
	AUTHORIZATION_INVALID = apperrors.AppError{
		Key: "AUTHORIZATION_INVALID",
		Code: "AUTHZ-VAL-001",
		Component: "authz_service",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	RESOURCE_OR_ACTION_REQUIRED = apperrors.AppError{
		Key: "RESOURCE_OR_ACTION_REQUIRED",
		Code: "AUTHZ-VAL-002",
		Component: "authz_service",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Resource and action are required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_REQUIRED = apperrors.AppError{
		Key: "ROLE_REQUIRED",
		Code: "AUTHZ-VAL-003",
		Component: "authz_service",
		Tags: []string{"validation","authz"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Role is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_NOT_FOUND = apperrors.AppError{
		Key: "ROLE_NOT_FOUND",
		Code: "AUTHZ-DOM-001",
		Component: "role_service",
		Tags: []string{"domain"},
		Status: 404,
		GRPCCode: "NotFound",
		Message: "Role not found",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_CONFLICT = apperrors.AppError{
		Key: "ROLE_CONFLICT",
		Code: "AUTHZ-DOM-002",
		Component: "role_service",
		Tags: []string{"domain"},
		Status: 409,
		GRPCCode: "AlreadyExists",
		Message: "Role already exists",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_INVALID = apperrors.AppError{
		Key: "ROLE_INVALID",
		Code: "AUTHZ-DOM-003",
		Component: "role_service",
		Tags: []string{"domain"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Role contains invalid references",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_PERSIST_FAILED = apperrors.AppError{
		Key: "ROLE_PERSIST_FAILED",
		Code: "AUTHZ-DOM-004",
		Component: "role_repository",
		Tags: []string{"domain"},
		Status: 500,
		GRPCCode: "Internal",
		Message: "Failed to persist role",
		Severity: "S2",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_FORBIDDEN = apperrors.AppError{
		Key: "ROLE_FORBIDDEN",
		Code: "AUTHZ-SEC-001",
		Component: "authz_service",
		Tags: []string{"security","authz"},
		Status: 403,
		GRPCCode: "PermissionDenied",
		Message: "Permission denied",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

)

var (
	REASON_VAL_REQUIRED = apperrors.AppErrorDetail{
		Code: "VAL_REQUIRED",
		Message: "Field is required",
	}

	REASON_VAL_INVALID_FORMAT = apperrors.AppErrorDetail{
		Code: "VAL_INVALID_FORMAT",
		Message: "Invalid format",
	}

	REASON_VAL_OUT_OF_RANGE = apperrors.AppErrorDetail{
		Code: "VAL_OUT_OF_RANGE",
		Message: "Out of range",
	}

	REASON_VAL_DUPLICATE = apperrors.AppErrorDetail{
		Code: "VAL_DUPLICATE",
		Message: "Duplicate value",
	}

	REASON_VAL_NOT_FOUND = apperrors.AppErrorDetail{
		Code: "VAL_NOT_FOUND",
		Message: "Not found",
	}

)

var ErrorByCode = map[string]apperrors.AppError{
	"AUTHZ-VAL-001": AUTHORIZATION_INVALID,
	"AUTHZ-VAL-002": RESOURCE_OR_ACTION_REQUIRED,
	"AUTHZ-VAL-003": ROLE_REQUIRED,
	"AUTHZ-DOM-001": ROLE_NOT_FOUND,
	"AUTHZ-DOM-002": ROLE_CONFLICT,
	"AUTHZ-DOM-003": ROLE_INVALID,
	"AUTHZ-DOM-004": ROLE_PERSIST_FAILED,
	"AUTHZ-SEC-001": ROLE_FORBIDDEN,
}

var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{
	"VAL_REQUIRED": REASON_VAL_REQUIRED,
	"VAL_INVALID_FORMAT": REASON_VAL_INVALID_FORMAT,
	"VAL_OUT_OF_RANGE": REASON_VAL_OUT_OF_RANGE,
	"VAL_DUPLICATE": REASON_VAL_DUPLICATE,
	"VAL_NOT_FOUND": REASON_VAL_NOT_FOUND,
}

