// Code generated by generate_errors.sh. DO NOT EDIT.

package errors

import "github.com/vokhanh12/refactor-rongstore-system/server/pkg/apperrors"

var (
	DOM_NONE = apperrors.AppError{
		Key: "DOM_NONE",
		Code: "NONE-DOM-001",
		Layer: "DOM",
		Component: "none",
		Tags: []string{"none"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	APP_NONE = apperrors.AppError{
		Key: "APP_NONE",
		Code: "NONE-APP-001",
		Layer: "APP",
		Component: "none",
		Tags: []string{"none"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	AUTHORIZATION_INVALID = apperrors.AppError{
		Key: "AUTHORIZATION_INVALID",
		Code: "AUTHZ-TRANS-001",
		Layer: "TRANS",
		Component: "authz_transport",
		Tags: []string{"transport"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Invalid authorization",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	RESOURCE_OR_ACTION_REQUIRED = apperrors.AppError{
		Key: "RESOURCE_OR_ACTION_REQUIRED",
		Code: "AUTHZ-TRANS-002",
		Layer: "TRANS",
		Component: "authz_transport",
		Tags: []string{"transport"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Resource and action are required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_REQUIRED = apperrors.AppError{
		Key: "ROLE_REQUIRED",
		Code: "AUTHZ-TRANS-003",
		Layer: "TRANS",
		Component: "authz_transport",
		Tags: []string{"transport"},
		Status: 400,
		GRPCCode: "InvalidArgument",
		Message: "Role is required",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

	ROLE_FORBIDDEN = apperrors.AppError{
		Key: "ROLE_FORBIDDEN",
		Code: "AUTHZ-SEC-001",
		Layer: "SEC",
		Component: "authz_service",
		Tags: []string{"security"},
		Status: 403,
		GRPCCode: "PermissionDenied",
		Message: "Permission denied",
		Severity: "S3",
		Retryable: false,
		Cause: "",
		ClientAction: "",
		ServerAction: "",
	}

)

var (
	REASON_VAL_REQUIRED = apperrors.AppErrorDetail{
		Code: "VAL_REQUIRED",
		Message: "Field is required",
	}

	REASON_VAL_NULL = apperrors.AppErrorDetail{
		Code: "VAL_NULL",
		Message: "Field must not be null",
	}

	REASON_VAL_INVALID_FORMAT = apperrors.AppErrorDetail{
		Code: "VAL_INVALID_FORMAT",
		Message: "Invalid format",
	}

	REASON_VAL_INVALID_TYPE = apperrors.AppErrorDetail{
		Code: "VAL_INVALID_TYPE",
		Message: "Invalid data type",
	}

	REASON_VAL_INVALID_ENUM = apperrors.AppErrorDetail{
		Code: "VAL_INVALID_ENUM",
		Message: "Invalid enum value",
	}

	REASON_VAL_OUT_OF_RANGE = apperrors.AppErrorDetail{
		Code: "VAL_OUT_OF_RANGE",
		Message: "Out of range",
	}

	REASON_VAL_TOO_SHORT = apperrors.AppErrorDetail{
		Code: "VAL_TOO_SHORT",
		Message: "Value is too short",
	}

	REASON_VAL_TOO_LONG = apperrors.AppErrorDetail{
		Code: "VAL_TOO_LONG",
		Message: "Value is too long",
	}

	REASON_APP_DUPLICATE = apperrors.AppErrorDetail{
		Code: "APP_DUPLICATE",
		Message: "Duplicate value",
	}

	REASON_APP_CONFLICT = apperrors.AppErrorDetail{
		Code: "APP_CONFLICT",
		Message: "Value conflicts with existing data",
	}

	REASON_APP_NOT_ALLOWED = apperrors.AppErrorDetail{
		Code: "APP_NOT_ALLOWED",
		Message: "Operation not allowed",
	}

	REASON_APP_FORBIDDEN_STATE = apperrors.AppErrorDetail{
		Code: "APP_FORBIDDEN_STATE",
		Message: "Invalid state for operation",
	}

	REASON_APP_NOT_FOUND = apperrors.AppErrorDetail{
		Code: "APP_NOT_FOUND",
		Message: "Not found",
	}

	REASON_APP_ALREADY_EXISTS = apperrors.AppErrorDetail{
		Code: "APP_ALREADY_EXISTS",
		Message: "Already exists",
	}

	REASON_PARSE_INVALID_REFERENCE = apperrors.AppErrorDetail{
		Code: "PARSE_INVALID_REFERENCE",
		Message: "Invalid reference",
	}

	REASON_PARSE_INVALID_TIME_RANGE = apperrors.AppErrorDetail{
		Code: "PARSE_INVALID_TIME_RANGE",
		Message: "Invalid time range",
	}

	REASON_SEC_UNSAFE_INPUT = apperrors.AppErrorDetail{
		Code: "SEC_UNSAFE_INPUT",
		Message: "Unsafe input detected",
	}

	REASON_SEC_INVALID = apperrors.AppErrorDetail{
		Code: "SEC_INVALID",
		Message: "Invalid value",
	}

)

var ErrorByCode = map[string]apperrors.AppError{
	"NONE-DOM-001": DOM_NONE,
	"NONE-APP-001": APP_NONE,
	"AUTHZ-TRANS-001": AUTHORIZATION_INVALID,
	"AUTHZ-TRANS-002": RESOURCE_OR_ACTION_REQUIRED,
	"AUTHZ-TRANS-003": ROLE_REQUIRED,
	"AUTHZ-SEC-001": ROLE_FORBIDDEN,
}

var ErrorDetailByCode = map[string]apperrors.AppErrorDetail{
	"VAL_REQUIRED": REASON_VAL_REQUIRED,
	"VAL_NULL": REASON_VAL_NULL,
	"VAL_INVALID_FORMAT": REASON_VAL_INVALID_FORMAT,
	"VAL_INVALID_TYPE": REASON_VAL_INVALID_TYPE,
	"VAL_INVALID_ENUM": REASON_VAL_INVALID_ENUM,
	"VAL_OUT_OF_RANGE": REASON_VAL_OUT_OF_RANGE,
	"VAL_TOO_SHORT": REASON_VAL_TOO_SHORT,
	"VAL_TOO_LONG": REASON_VAL_TOO_LONG,
	"APP_DUPLICATE": REASON_APP_DUPLICATE,
	"APP_CONFLICT": REASON_APP_CONFLICT,
	"APP_NOT_ALLOWED": REASON_APP_NOT_ALLOWED,
	"APP_FORBIDDEN_STATE": REASON_APP_FORBIDDEN_STATE,
	"APP_NOT_FOUND": REASON_APP_NOT_FOUND,
	"APP_ALREADY_EXISTS": REASON_APP_ALREADY_EXISTS,
	"PARSE_INVALID_REFERENCE": REASON_PARSE_INVALID_REFERENCE,
	"PARSE_INVALID_TIME_RANGE": REASON_PARSE_INVALID_TIME_RANGE,
	"SEC_UNSAFE_INPUT": REASON_SEC_UNSAFE_INPUT,
	"SEC_INVALID": REASON_SEC_INVALID,
}

