syntax = "proto3";

package common.v1;
option go_package = "github.com/vokhanh12/refactor-rongstore-system/server/gen/proto/core/common/v1;commonv1"; 

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

message BaseRequest {

  google.protobuf.Timestamp request_date_time = 1;

  string request_id = 2 [
    (buf.validate.field).string.uuid = true
  ];

  string language = 3 [
    (buf.validate.field).string.min_len = 1
  ];

  string user_agent = 4 [
    (buf.validate.field).string.min_len = 1
  ];
}